import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "ar" | "en" | "fr" | "tr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar");

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, []);

  const t = useCallback(
    (key: string) => {
      const keys = key.split(".");
      let value: any = translations[language];
      for (const k of keys) {
        value = value?.[k];
      }
      return (value as string) ?? key;
    },
    [language]
  );

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations: Record<Language, Record<string, any>> = {
  ar: {
    nav: {
      home: "الرئيسية",
      wings: "أجنحة المتحف",
      locations: "المواقع",
      technologies: "التقنيات",
      planVisit: "خطط زيارتك",
      bookTicket: "احجز تذكرتك",
    },
    hero: {
      badge: "السيرة كأنك تعيشها",
      titleLine1: "المتحف الدولي",
      titleLine2: "للسيرة النبوية",
      description: "اختبر الإرث العميق للنبي محمد ﷺ من خلال التكنولوجيا الأصيلة والقصص الغامرة عبر",
      descriptionLine2: "خمسة مواقع مرموقة حول العالم",
      bookVisit: "احجز زيارتك",
      availableIn: "متاح باللغات:",
      langRussian: "الروسية",
      langTurkish: "التركية",
      langIndonesian: "الإندونيسية",
      langUrdu: "الأردية",
      langFrench: "الفرنسية",
      langEnglish: "الإنجليزية",
      langArabic: "العربية",
    },
    wings: {
      sectionTitle: "أجنحة المتحف",
      sectionDescription: "رحلة روحية وتاريخية عبر 14 جناحًا، كل منها يروي قصة فريدة من قصص الإيمان والتاريخ الإسلامي",
      statWings: "جناح متميز",
      statMaterials: "مادة علمية",
      statExperience: "تجربة روحية",
      moreWings: "المزيد من الأجنحة",
      showing: "عرض",
      of: "من",
      wing: "جناح",
      exploreWing: "استكشف الجناح",
      prev: "السابق",
      next: "التالي",
      goTo: "الانتقال إلى",
      wing1Title: "التحيات لله، عزَّ وجلَّ",
      wing1Desc: "تعريف شامل بالله وأسمائه وصفاته ودلائل قدرته، مستخلص من مئة ألف مادة وموضوع.",
      wing2Title: "أثاث النبي ﷺ ومقتنياته",
      wing2Desc: "تجربة فريدة تعرض كل ما استخدمه النبي ﷺ من أثاث وأوانٍ ومقتنيات مع تعريف بها وما ورد عنها في السنة.",
      wing3Title: "طريق الهجرة",
      wing3Desc: "عرض لمسار هجرة النبي ﷺ إلى المدينة وأهم المواقف التي مر بها.",
      wing4Title: "النبي ﷺ والمرأة",
      wing4Desc: "عرض شامل يبرز مكانة المرأة في زمن النبي ﷺ ولائحة شرف تضم أكثر من 350 تشريفًا.",
      wing5Title: "النبي ﷺ والطفل",
      wing5Desc: "عرض يُظهر أكثر من 250 موقفًا محمودًا للأطفال مع النبي ﷺ.",
      wing6Title: "خيمة الطب النبوي",
      wing6Desc: "عرض علمي لما ورد في القرآن والسنة عن الأمراض والعلاج والأطعمة المفيدة.",
      wing7Title: "فضائل النبي ﷺ وشمائله",
      wing7Desc: "تفاصيل عن أسماء النبي ﷺ وصفاته ولباسه وطعامه وهيئته.",
      wing8Title: "النبي ﷺ كأنك معه",
      wing8Desc: "عرض إبداعي لحياة النبي ﷺ في مكة والمدينة باستخدام تقنيات مميزة.",
      wing9Title: "النبي ﷺ كأنك معه (نسخة مختلفة)",
      wing9Desc: "نفس الفكرة لكن بتجربة عرض مختلفة بصريًا.",
      wing10Title: "السلام عليك أيها النبي ﷺ",
      wing10Desc: "تلخيص زمني لأحداث السيرة النبوية من الميلاد حتى الوفاة.",
      wing11Title: "الحجرة النبوية الشريفة",
      wing11Desc: "وصف دقيق للحجرة الشريفة ومساحتها وأحداثها.",
      wing12Title: "النبي ﷺ كأنك تراه",
      wing12Desc: "عرض شامل لحياة النبي ﷺ وصفاته ومعالم شخصيته.",
      wing13Title: "الأنبياء كأنك تراهم",
      wing13Desc: "عرض مميز للأنبياء، أزمانهم، معجزاتهم، وآدابهم.",
      wing14Title: "جناح إضافي",
      wing14Desc: "يُترك بتصميم متناسق لعرض جناح مستقبلي.",
    },
    tech: {
      badge: "تقنيات مبتكرة",
      sectionTitle: "تقنيات المتحف",
      sectionDescription: "اكتشف أحدث التقنيات التفاعلية التي تجعل تجربتك في المتحف فريدة ومميزة",
      immersiveRooms: "الغرف الانغماسية",
      atlases3d: "الأطالس ثلاثية الأبعاد",
      hologram: "الهولوجرام",
      ai: "الذكاء الاصطناعي",
      cinemaHalls: "قاعات السينما",
      interactiveScreens: "الشاشات التفاعلية",
      interactiveMurals: "الجداريات التفاعلية",
      models3d: "المجسمات ثلاثية الأبعاد",
      childrenRooms: "غرف تفاعلية للأطفال",
      interactiveArtifacts: "المقتنيات التفاعلية",
      vr: "الواقع الافتراضي",
      interactiveModels: "النماذج التفاعلية",
    },
    planVisit: {
      sectionTitle: "خطط زيارتك",
      sectionDescription: "كل ما تحتاج معرفته لتجربة متحف غنية",
      feature1Title: "آمن ومضمون",
      feature1Desc: "احجز بثقة من خلال نظام الدفع المشفر الذي يحمي معلوماتك الشخصية",
      feature2Title: "احجز مسبقاً",
      feature2Desc: "احجز التاريخ والوقت المفضل لديك عبر الإنترنت لضمان التوفر وتجنب الانتظار في الطوابير",
      feature3Title: "للجميع",
      feature3Desc: "مثالي للعائلات والطلاب والباحثين والزوار من جميع أنحاء العالم الذين يسعون لاستكشاف التراث الإسلامي",
    },
    locations: {
      sectionTitle: "مواقعنا العالمية",
      sectionSubtitle: "قم بزيارة متاحفنا ذات المستوى العالمي في ثلاث قارات",
      sectionQuestion: "أي فرع ترغب في زيارته؟",
      openNow: "مفتوح الآن",
      ticketsFrom: "تبدأ التذاكر من",
      bookVisit: "احجز زيارة",
      visitInfo: "معلومات الزيارة",
      visitInfoDesc: "كل ما تحتاج معرفته لزيارتك",
      whatsIncluded: "ما يشمله",
      durationTiming: "المدة والتوقيت",
      duration: "المدة:",
      workingHours: "ساعات العمل:",
      cancellationPolicy: "سياسة الإلغاء",
      mecca: "مكة المكرمة",
      medina: "المدينة المنورة",
      rabat: "الرباط",
      nouakchott: "نواكشوط",
      dakar: "داكار",
      countrySA: "المملكة العربية السعودية",
      countryMorocco: "المملكة المغربية",
      countryMauritania: "موريتانيا",
      countrySenegal: "السنغال",
      addressMecca: "وقف الملك عبدالعزيز رحمه الله برج الساعة الدور الثاني",
      addressMedina: "الساحة الجنوبية للمسجد النبوي الشريف مقابل الروضة",
      addressRabat: "مبنى اليونيسكو",
      addressNouakchott: "أدخل عنوان فرع نواكشوط هنا",
      addressDakar: "أدخل عنوان فرع داكار هنا",
      guidedTour: "جولة إرشادية باللغة التي تفضلها",
      allSections60: "الدخول إلى جميع أقسام المعرض الـ 60+",
      allSections: "الدخول إلى جميع أقسام المعرض",
      interactiveDisplays3d: "تجربة العروض التفاعلية والنماذج ثلاثية الأبعاد",
      interactiveDisplays: "تجربة العروض التفاعلية",
      cinemaExperience: "تجربة قاعة السينما",
      freeGuide: "كتيب إرشادي مجاني للمتحف",
      duration23: "2-3 ساعات",
      hoursSatThu: "السبت - الخميس 9:00 صباحاً - 9:00 مساءً",
      hoursMonSat: "الإثنين - السبت 10:00 صباحاً - 8:00 مساءً",
      hoursMonSat2: "الإثنين - السبت 10:00 صباحاً - 6:00 مساءً",
      hoursSatThu2: "السبت - الخميس 9:00 صباحاً - 6:00 مساءً",
      closedFri: "مغلق أيام الجمعة",
      closedSun: "مغلق أيام الأحد",
      cancel24: "إلغاء مجاني قبل 24 ساعة من موعد الزيارة",
      cancel48: "إلغاء مجاني قبل 48 ساعة من موعد الزيارة",
      noRefund24: "لا يوجد استرداد للإلغاء خلال 24 ساعة",
      noRefund48: "لا يوجد استرداد للإلغاء خلال 48 ساعة",
      reschedule: "إعادة الجدولة متاحة حسب التوفر",
    },
    testimonials: {
      sectionTitle: "ماذا يقول زوارنا",
      sectionDescription: "اكتشف تجارب الزوار من جميع أنحاء العالم",
      pages: "صفحات",
      of: "من",
      t1text: "تجربة خلابة تماماً! العروض الغامرة والنماذج التاريخية أحيت حياة الرسول ﷺ بشكل واقعي. يجب زيارتها لأي شخص يسعى لفهم التراث الإسلامي.",
      t1highlight: "تجربة خلابة تماماً!",
      t1name: "فاطمة حسن",
      t1location: "زارت فرع مكة المكرمة",
      t2text: "التقنية التفاعلية والمعروضات الجميلة جعلت التعلم عن الحضارة الإسلامية جذاباً لعائلتنا بأكملها. كان الأطفال مفتونين بشكل خاص بنماذج المدن ثلاثية الأبعاد.",
      t2highlight: "التقنية التفاعلية والمعروضات الجميلة",
      t2name: "أحمد الراشد",
      t2location: "زار فرع المدينة المنورة",
      t3text: "متحف عالمي المستوى يجمع بين التكنولوجيا الحديثة والاحترام العميق للتاريخ. كانت الجولات متعددة اللغات ممتازة، والموظفون كانوا ذوي معرفة واسعة ومرحبين للغاية.",
      t3highlight: "متحف عالمي المستوى",
      t3name: "محمد بنزيمة",
      t3location: "زار فرع الرباط",
      t4text: "زيارة روحانية لا تُنسى! شعرت بالقرب من سيرة النبي ﷺ بطريقة لم أتخيلها من قبل. المكان يفيض بالسكينة والإيمان.",
      t4highlight: "زيارة روحانية لا تُنسى!",
      t4name: "عائشة المنصوري",
      t4location: "زارت فرع دبي",
      t5text: "أفضل تجربة ثقافية مررت بها. التفاصيل الدقيقة في كل جناح تظهر مدى الاهتمام والحب الذي بُني به هذا المتحف.",
      t5highlight: "أفضل تجربة ثقافية مررت بها.",
      t5name: "خالد العتيبي",
      t5location: "زار فرع جدة",
      t6text: "أخذت والديّ في جولة وكانا سعيدين جداً. التصميم يراعي جميع الأعمار ويقدم المعلومات بأسلوب سلس ومؤثر.",
      t6highlight: "التصميم يراعي جميع الأعمار",
      t6name: "سارة القحطاني",
      t6location: "زارت فرع الرياض",
      t7text: "تجربة تعليمية رائعة للأطفال والكبار على حد سواء. أنصح كل عائلة بزيارة هذا المتحف.",
      t7highlight: "تجربة تعليمية رائعة",
      t7name: "يوسف الحربي",
      t7location: "زار فرع الدمام",
      t8text: "المتحف يجسد السيرة النبوية بشكل مبهر. خرجت وأنا أشعر بالفخر بتاريخنا الإسلامي العريق.",
      t8highlight: "المتحف يجسد السيرة النبوية بشكل مبهر.",
      t8name: "نورة السبيعي",
      t8location: "زارت فرع الكويت",
    },
    footer: {
      description: "متحف عالمي يحتفي بالتراث الإسلامي ويروي قصة الرسول ﷺ من خلال أحدث التقنيات والمعروضات التفاعلية.",
      quickLinks: "روابط سريعة",
      home: "الرئيسية",
      aboutMuseum: "عن المتحف",
      exhibitions: "المعارض",
      events: "الفعاليات",
      contactUs: "تواصل معنا",
      branches: "فروعنا",
      branchMecca: "فرع مكة المكرمة",
      branchMedina: "فرع المدينة المنورة",
      branchRabat: "فرع الرباط",
      branchNouakchott: "فرع نواكشوط",
      branchDakar: "فرع داكار",
      contactTitle: "تواصل معنا",
      address: "مكة المكرمة، المملكة العربية السعودية",
      copyright: "© 2024 متحف السيرة النبوية. جميع الحقوق محفوظة.",
      privacy: "سياسة الخصوصية",
      terms: "الشروط والأحكام",
    },
  },
  en: {
    nav: {
      home: "Home",
      wings: "Museum Wings",
      locations: "Locations",
      technologies: "Technologies",
      planVisit: "Plan Your Visit",
      bookTicket: "Book Ticket",
    },
    hero: {
      badge: "Experience the Seerah",
      titleLine1: "The International",
      titleLine2: "Seerah Museum",
      description: "Experience the profound legacy of Prophet Muhammad ﷺ through authentic technology and immersive storytelling across",
      descriptionLine2: "five prestigious locations worldwide",
      bookVisit: "Book Your Visit",
      availableIn: "Available in:",
      langRussian: "Russian",
      langTurkish: "Turkish",
      langIndonesian: "Indonesian",
      langUrdu: "Urdu",
      langFrench: "French",
      langEnglish: "English",
      langArabic: "Arabic",
    },
    wings: {
      sectionTitle: "Museum Wings",
      sectionDescription: "A spiritual and historical journey through 14 wings, each telling a unique story of faith and Islamic history",
      statWings: "Distinct Wings",
      statMaterials: "Scientific Materials",
      statExperience: "Spiritual Experience",
      moreWings: "More Wings",
      showing: "Showing",
      of: "of",
      wing: "wings",
      exploreWing: "Explore Wing",
      prev: "Previous",
      next: "Next",
      goTo: "Go to",
      wing1Title: "Praises to Allah, the Almighty",
      wing1Desc: "A comprehensive introduction to Allah, His names, attributes, and signs of His power, drawn from 100,000 materials and topics.",
      wing2Title: "The Prophet's ﷺ Furnishings & Belongings",
      wing2Desc: "A unique experience showcasing everything used by the Prophet ﷺ including furniture, vessels, and belongings with descriptions from the Sunnah.",
      wing3Title: "The Hijrah Route",
      wing3Desc: "A display of the Prophet's ﷺ migration path to Medina and the key events along the way.",
      wing4Title: "The Prophet ﷺ and Women",
      wing4Desc: "A comprehensive display highlighting women's status during the Prophet's ﷺ era with an honor list of over 350 recognitions.",
      wing5Title: "The Prophet ﷺ and Children",
      wing5Desc: "A display showcasing over 250 praiseworthy interactions of children with the Prophet ﷺ.",
      wing6Title: "Prophetic Medicine Tent",
      wing6Desc: "A scientific exhibition on diseases, treatments, and beneficial foods mentioned in the Quran and Sunnah.",
      wing7Title: "Virtues & Characteristics of the Prophet ﷺ",
      wing7Desc: "Details about the Prophet's ﷺ names, attributes, clothing, food, and appearance.",
      wing8Title: "As If You Were With the Prophet ﷺ",
      wing8Desc: "A creative display of the Prophet's ﷺ life in Mecca and Medina using distinctive technologies.",
      wing9Title: "As If You Were With the Prophet ﷺ (Alternate)",
      wing9Desc: "Same concept with a different visual presentation experience.",
      wing10Title: "Peace Be Upon You, O Prophet ﷺ",
      wing10Desc: "A chronological summary of Seerah events from birth to passing.",
      wing11Title: "The Noble Prophet's Chamber",
      wing11Desc: "A precise description of the noble chamber, its dimensions, and events.",
      wing12Title: "The Prophet ﷺ As If You See Him",
      wing12Desc: "A comprehensive display of the Prophet's ﷺ life, attributes, and personality traits.",
      wing13Title: "The Prophets As If You See Them",
      wing13Desc: "A distinctive display of the prophets, their eras, miracles, and manners.",
      wing14Title: "Additional Wing",
      wing14Desc: "Reserved for a future wing with consistent design.",
    },
    tech: {
      badge: "Innovative Technologies",
      sectionTitle: "Museum Technologies",
      sectionDescription: "Discover the latest interactive technologies that make your museum experience unique and memorable",
      immersiveRooms: "Immersive Rooms",
      atlases3d: "3D Atlases",
      hologram: "Hologram",
      ai: "Artificial Intelligence",
      cinemaHalls: "Cinema Halls",
      interactiveScreens: "Interactive Screens",
      interactiveMurals: "Interactive Murals",
      models3d: "3D Models",
      childrenRooms: "Interactive Children's Rooms",
      interactiveArtifacts: "Interactive Artifacts",
      vr: "Virtual Reality (VR)",
      interactiveModels: "Interactive Models",
    },
    planVisit: {
      sectionTitle: "Plan Your Visit",
      sectionDescription: "Everything you need to know for a rich museum experience",
      feature1Title: "Safe & Secure",
      feature1Desc: "Book with confidence through our encrypted payment system that protects your personal information",
      feature2Title: "Book in Advance",
      feature2Desc: "Reserve your preferred date and time online to ensure availability and avoid waiting in queues",
      feature3Title: "For Everyone",
      feature3Desc: "Perfect for families, students, researchers, and visitors from around the world seeking to explore Islamic heritage",
    },
    locations: {
      sectionTitle: "Our Global Locations",
      sectionSubtitle: "Visit our world-class museums across three continents",
      sectionQuestion: "Which branch would you like to visit?",
      openNow: "Open Now",
      ticketsFrom: "Tickets start from",
      bookVisit: "Book a visit to",
      visitInfo: "Visit Information",
      visitInfoDesc: "Everything you need to know for your visit",
      whatsIncluded: "What's Included",
      durationTiming: "Duration & Timing",
      duration: "Duration:",
      workingHours: "Working Hours:",
      cancellationPolicy: "Cancellation Policy",
      mecca: "Makkah",
      medina: "Madinah",
      rabat: "Rabat",
      nouakchott: "Nouakchott",
      dakar: "Dakar",
      countrySA: "Saudi Arabia",
      countryMorocco: "Morocco",
      countryMauritania: "Mauritania",
      countrySenegal: "Senegal",
      addressMecca: "King Abdulaziz Endowment, Clock Tower, 2nd Floor",
      addressMedina: "South Courtyard of the Prophet's Mosque, opposite Al-Rawdah",
      addressRabat: "UNESCO Building",
      addressNouakchott: "Nouakchott Branch Address",
      addressDakar: "Dakar Branch Address",
      guidedTour: "Guided tour in your preferred language",
      allSections60: "Access to all 60+ exhibition sections",
      allSections: "Access to all exhibition sections",
      interactiveDisplays3d: "Interactive displays and 3D models experience",
      interactiveDisplays: "Interactive displays experience",
      cinemaExperience: "Cinema hall experience",
      freeGuide: "Free museum guidebook",
      duration23: "2-3 hours",
      hoursSatThu: "Saturday - Thursday 9:00 AM - 9:00 PM",
      hoursMonSat: "Monday - Saturday 10:00 AM - 8:00 PM",
      hoursMonSat2: "Monday - Saturday 10:00 AM - 6:00 PM",
      hoursSatThu2: "Saturday - Thursday 9:00 AM - 6:00 PM",
      closedFri: "Closed on Fridays",
      closedSun: "Closed on Sundays",
      cancel24: "Free cancellation up to 24 hours before visit",
      cancel48: "Free cancellation up to 48 hours before visit",
      noRefund24: "No refund for cancellation within 24 hours",
      noRefund48: "No refund for cancellation within 48 hours",
      reschedule: "Rescheduling available based on availability",
    },
    testimonials: {
      sectionTitle: "What Our Visitors Say",
      sectionDescription: "Discover experiences from visitors around the world",
      pages: "pages",
      of: "of",
      t1text: "An absolutely breathtaking experience! The immersive displays and historical models brought the life of the Prophet ﷺ to life. A must-visit for anyone seeking to understand Islamic heritage.",
      t1highlight: "An absolutely breathtaking experience!",
      t1name: "Fatima Hassan",
      t1location: "Visited Makkah Branch",
      t2text: "The interactive technology and beautiful exhibits made learning about Islamic civilization engaging for our entire family. The children were especially fascinated by the 3D city models.",
      t2highlight: "The interactive technology and beautiful exhibits",
      t2name: "Ahmed Al-Rashed",
      t2location: "Visited Madinah Branch",
      t3text: "A world-class museum that combines modern technology with deep respect for history. The multilingual tours were excellent, and the staff were knowledgeable and very welcoming.",
      t3highlight: "A world-class museum",
      t3name: "Mohammed Benzema",
      t3location: "Visited Rabat Branch",
      t4text: "An unforgettable spiritual visit! I felt close to the Prophet's ﷺ Seerah in a way I never imagined before. The place overflows with tranquility and faith.",
      t4highlight: "An unforgettable spiritual visit!",
      t4name: "Aisha Al-Mansoori",
      t4location: "Visited Dubai Branch",
      t5text: "The best cultural experience I've ever had. The meticulous details in every wing show the care and love with which this museum was built.",
      t5highlight: "The best cultural experience I've ever had.",
      t5name: "Khalid Al-Otaibi",
      t5location: "Visited Jeddah Branch",
      t6text: "I took my parents on a tour and they were so happy. The design caters to all ages and presents information in a smooth and impactful way.",
      t6highlight: "The design caters to all ages",
      t6name: "Sara Al-Qahtani",
      t6location: "Visited Riyadh Branch",
      t7text: "A wonderful educational experience for children and adults alike. I recommend every family visit this museum.",
      t7highlight: "A wonderful educational experience",
      t7name: "Youssef Al-Harbi",
      t7location: "Visited Dammam Branch",
      t8text: "The museum embodies the Prophet's Seerah magnificently. I left feeling proud of our rich Islamic history.",
      t8highlight: "The museum embodies the Prophet's Seerah magnificently.",
      t8name: "Noura Al-Subaie",
      t8location: "Visited Kuwait Branch",
    },
    footer: {
      description: "A global museum celebrating Islamic heritage and telling the story of the Prophet ﷺ through the latest technologies and interactive exhibits.",
      quickLinks: "Quick Links",
      home: "Home",
      aboutMuseum: "About the Museum",
      exhibitions: "Exhibitions",
      events: "Events",
      contactUs: "Contact Us",
      branches: "Our Branches",
      branchMecca: "Makkah Branch",
      branchMedina: "Madinah Branch",
      branchRabat: "Rabat Branch",
      branchNouakchott: "Nouakchott Branch",
      branchDakar: "Dakar Branch",
      contactTitle: "Contact Us",
      address: "Makkah, Saudi Arabia",
      copyright: "© 2024 Seerah Museum. All rights reserved.",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
    },
  },
  fr: {
    nav: {
      home: "Accueil",
      wings: "Ailes du Musée",
      locations: "Emplacements",
      technologies: "Technologies",
      planVisit: "Planifiez Votre Visite",
      bookTicket: "Réserver un Billet",
    },
    hero: {
      badge: "Vivez la Sîra",
      titleLine1: "Le Musée International",
      titleLine2: "de la Sîra du Prophète",
      description: "Découvrez l'héritage profond du Prophète Muhammad ﷺ à travers des technologies authentiques et des récits immersifs dans",
      descriptionLine2: "cinq sites prestigieux à travers le monde",
      bookVisit: "Réservez Votre Visite",
      availableIn: "Disponible en :",
      langRussian: "Russe",
      langTurkish: "Turc",
      langIndonesian: "Indonésien",
      langUrdu: "Ourdou",
      langFrench: "Français",
      langEnglish: "Anglais",
      langArabic: "Arabe",
    },
    wings: {
      sectionTitle: "Ailes du Musée",
      sectionDescription: "Un voyage spirituel et historique à travers 14 ailes, chacune racontant une histoire unique de foi et d'histoire islamique",
      statWings: "Ailes Distinctes",
      statMaterials: "Matériaux Scientifiques",
      statExperience: "Expérience Spirituelle",
      moreWings: "Plus d'Ailes",
      showing: "Affichage",
      of: "de",
      wing: "ailes",
      exploreWing: "Explorer l'Aile",
      prev: "Précédent",
      next: "Suivant",
      goTo: "Aller à",
      wing1Title: "Louanges à Allah, le Tout-Puissant",
      wing1Desc: "Une introduction complète à Allah, Ses noms, attributs et signes de Sa puissance, tirée de 100 000 matériaux et sujets.",
      wing2Title: "Mobilier et Effets du Prophète ﷺ",
      wing2Desc: "Une expérience unique présentant tout ce que le Prophète ﷺ a utilisé, y compris meubles, récipients et effets personnels avec des descriptions de la Sunna.",
      wing3Title: "La Route de la Hijra",
      wing3Desc: "Une présentation du chemin de migration du Prophète ﷺ vers Médine et les événements clés en chemin.",
      wing4Title: "Le Prophète ﷺ et les Femmes",
      wing4Desc: "Une présentation complète mettant en lumière le statut des femmes à l'époque du Prophète ﷺ avec une liste d'honneur de plus de 350 reconnaissances.",
      wing5Title: "Le Prophète ﷺ et les Enfants",
      wing5Desc: "Une présentation de plus de 250 interactions louables des enfants avec le Prophète ﷺ.",
      wing6Title: "Tente de Médecine Prophétique",
      wing6Desc: "Une exposition scientifique sur les maladies, traitements et aliments bénéfiques mentionnés dans le Coran et la Sunna.",
      wing7Title: "Vertus et Caractéristiques du Prophète ﷺ",
      wing7Desc: "Détails sur les noms, attributs, vêtements, nourriture et apparence du Prophète ﷺ.",
      wing8Title: "Comme Si Vous Étiez Avec le Prophète ﷺ",
      wing8Desc: "Une présentation créative de la vie du Prophète ﷺ à La Mecque et Médine utilisant des technologies distinctives.",
      wing9Title: "Comme Si Vous Étiez Avec le Prophète ﷺ (Alternatif)",
      wing9Desc: "Même concept avec une expérience de présentation visuelle différente.",
      wing10Title: "Paix Sur Vous, Ô Prophète ﷺ",
      wing10Desc: "Un résumé chronologique des événements de la Sîra de la naissance au décès.",
      wing11Title: "La Noble Chambre du Prophète",
      wing11Desc: "Une description précise de la noble chambre, ses dimensions et événements.",
      wing12Title: "Le Prophète ﷺ Comme Si Vous Le Voyez",
      wing12Desc: "Une présentation complète de la vie, des attributs et des traits de personnalité du Prophète ﷺ.",
      wing13Title: "Les Prophètes Comme Si Vous Les Voyez",
      wing13Desc: "Une présentation distinctive des prophètes, leurs époques, miracles et manières.",
      wing14Title: "Aile Supplémentaire",
      wing14Desc: "Réservée pour une future aile avec un design cohérent.",
    },
    tech: {
      badge: "Technologies Innovantes",
      sectionTitle: "Technologies du Musée",
      sectionDescription: "Découvrez les dernières technologies interactives qui rendent votre expérience muséale unique et mémorable",
      immersiveRooms: "Salles Immersives",
      atlases3d: "Atlas 3D",
      hologram: "Hologramme",
      ai: "Intelligence Artificielle",
      cinemaHalls: "Salles de Cinéma",
      interactiveScreens: "Écrans Interactifs",
      interactiveMurals: "Fresques Interactives",
      models3d: "Modèles 3D",
      childrenRooms: "Salles Interactives pour Enfants",
      interactiveArtifacts: "Artefacts Interactifs",
      vr: "Réalité Virtuelle (VR)",
      interactiveModels: "Modèles Interactifs",
    },
    planVisit: {
      sectionTitle: "Planifiez Votre Visite",
      sectionDescription: "Tout ce que vous devez savoir pour une expérience muséale enrichissante",
      feature1Title: "Sûr et Sécurisé",
      feature1Desc: "Réservez en toute confiance grâce à notre système de paiement chiffré qui protège vos informations personnelles",
      feature2Title: "Réservez à l'Avance",
      feature2Desc: "Réservez votre date et heure préférées en ligne pour garantir la disponibilité et éviter les files d'attente",
      feature3Title: "Pour Tous",
      feature3Desc: "Parfait pour les familles, étudiants, chercheurs et visiteurs du monde entier souhaitant explorer le patrimoine islamique",
    },
    locations: {
      sectionTitle: "Nos Sites Mondiaux",
      sectionSubtitle: "Visitez nos musées de classe mondiale sur trois continents",
      sectionQuestion: "Quelle branche souhaitez-vous visiter ?",
      openNow: "Ouvert Maintenant",
      ticketsFrom: "Billets à partir de",
      bookVisit: "Réserver une visite à",
      visitInfo: "Informations de Visite",
      visitInfoDesc: "Tout ce que vous devez savoir pour votre visite",
      whatsIncluded: "Ce qui est inclus",
      durationTiming: "Durée et Horaires",
      duration: "Durée :",
      workingHours: "Heures d'ouverture :",
      cancellationPolicy: "Politique d'Annulation",
      mecca: "La Mecque",
      medina: "Médine",
      rabat: "Rabat",
      nouakchott: "Nouakchott",
      dakar: "Dakar",
      countrySA: "Arabie Saoudite",
      countryMorocco: "Maroc",
      countryMauritania: "Mauritanie",
      countrySenegal: "Sénégal",
      addressMecca: "Waqf du Roi Abdulaziz, Tour de l'Horloge, 2e étage",
      addressMedina: "Cour sud de la Mosquée du Prophète, face à Al-Rawdah",
      addressRabat: "Bâtiment UNESCO",
      addressNouakchott: "Adresse de la branche de Nouakchott",
      addressDakar: "Adresse de la branche de Dakar",
      guidedTour: "Visite guidée dans la langue de votre choix",
      allSections60: "Accès à plus de 60 sections d'exposition",
      allSections: "Accès à toutes les sections d'exposition",
      interactiveDisplays3d: "Expérience de présentations interactives et modèles 3D",
      interactiveDisplays: "Expérience de présentations interactives",
      cinemaExperience: "Expérience de la salle de cinéma",
      freeGuide: "Guide gratuit du musée",
      duration23: "2-3 heures",
      hoursSatThu: "Samedi - Jeudi 9h00 - 21h00",
      hoursMonSat: "Lundi - Samedi 10h00 - 20h00",
      hoursMonSat2: "Lundi - Samedi 10h00 - 18h00",
      hoursSatThu2: "Samedi - Jeudi 9h00 - 18h00",
      closedFri: "Fermé le vendredi",
      closedSun: "Fermé le dimanche",
      cancel24: "Annulation gratuite jusqu'à 24 heures avant la visite",
      cancel48: "Annulation gratuite jusqu'à 48 heures avant la visite",
      noRefund24: "Aucun remboursement pour annulation dans les 24 heures",
      noRefund48: "Aucun remboursement pour annulation dans les 48 heures",
      reschedule: "Reprogrammation disponible selon la disponibilité",
    },
    testimonials: {
      sectionTitle: "Ce que Disent Nos Visiteurs",
      sectionDescription: "Découvrez les expériences de visiteurs du monde entier",
      pages: "pages",
      of: "de",
      t1text: "Une expérience absolument époustouflante ! Les présentations immersives et les modèles historiques ont donné vie à la vie du Prophète ﷺ. Un incontournable pour quiconque cherche à comprendre le patrimoine islamique.",
      t1highlight: "Une expérience absolument époustouflante !",
      t1name: "Fatima Hassan",
      t1location: "A visité la branche de La Mecque",
      t2text: "La technologie interactive et les belles expositions ont rendu l'apprentissage de la civilisation islamique captivant pour toute notre famille. Les enfants étaient particulièrement fascinés par les modèles 3D des villes.",
      t2highlight: "La technologie interactive et les belles expositions",
      t2name: "Ahmed Al-Rashed",
      t2location: "A visité la branche de Médine",
      t3text: "Un musée de classe mondiale qui allie technologie moderne et profond respect de l'histoire. Les visites multilingues étaient excellentes et le personnel était compétent et très accueillant.",
      t3highlight: "Un musée de classe mondiale",
      t3name: "Mohammed Benzema",
      t3location: "A visité la branche de Rabat",
      t4text: "Une visite spirituelle inoubliable ! Je me suis senti proche de la Sîra du Prophète ﷺ d'une manière que je n'avais jamais imaginée. Le lieu déborde de sérénité et de foi.",
      t4highlight: "Une visite spirituelle inoubliable !",
      t4name: "Aisha Al-Mansoori",
      t4location: "A visité la branche de Dubaï",
      t5text: "La meilleure expérience culturelle que j'aie jamais eue. Les détails minutieux dans chaque aile montrent le soin et l'amour avec lesquels ce musée a été construit.",
      t5highlight: "La meilleure expérience culturelle que j'aie jamais eue.",
      t5name: "Khalid Al-Otaibi",
      t5location: "A visité la branche de Djeddah",
      t6text: "J'ai emmené mes parents en visite et ils étaient très heureux. Le design convient à tous les âges et présente les informations de manière fluide et percutante.",
      t6highlight: "Le design convient à tous les âges",
      t6name: "Sara Al-Qahtani",
      t6location: "A visité la branche de Riyad",
      t7text: "Une merveilleuse expérience éducative pour les enfants et les adultes. Je recommande à chaque famille de visiter ce musée.",
      t7highlight: "Une merveilleuse expérience éducative",
      t7name: "Youssef Al-Harbi",
      t7location: "A visité la branche de Dammam",
      t8text: "Le musée incarne magnifiquement la Sîra du Prophète. J'en suis ressorti fier de notre riche histoire islamique.",
      t8highlight: "Le musée incarne magnifiquement la Sîra du Prophète.",
      t8name: "Noura Al-Subaie",
      t8location: "A visité la branche du Koweït",
    },
    footer: {
      description: "Un musée mondial célébrant le patrimoine islamique et racontant l'histoire du Prophète ﷺ à travers les dernières technologies et expositions interactives.",
      quickLinks: "Liens Rapides",
      home: "Accueil",
      aboutMuseum: "À Propos du Musée",
      exhibitions: "Expositions",
      events: "Événements",
      contactUs: "Contactez-Nous",
      branches: "Nos Branches",
      branchMecca: "Branche de La Mecque",
      branchMedina: "Branche de Médine",
      branchRabat: "Branche de Rabat",
      branchNouakchott: "Branche de Nouakchott",
      branchDakar: "Branche de Dakar",
      contactTitle: "Contactez-Nous",
      address: "La Mecque, Arabie Saoudite",
      copyright: "© 2024 Musée de la Sîra. Tous droits réservés.",
      privacy: "Politique de Confidentialité",
      terms: "Conditions Générales",
    },
  },
  tr: {
    nav: {
      home: "Ana Sayfa",
      wings: "Müze Kanatları",
      locations: "Konumlar",
      technologies: "Teknolojiler",
      planVisit: "Ziyaretinizi Planlayın",
      bookTicket: "Bilet Al",
    },
    hero: {
      badge: "Sîreyi Yaşayın",
      titleLine1: "Uluslararası",
      titleLine2: "Siyer Müzesi",
      description: "Hz. Muhammed ﷺ'in derin mirasını özgün teknoloji ve sürükleyici hikâye anlatımıyla keşfedin",
      descriptionLine2: "dünya genelinde beş prestijli lokasyonda",
      bookVisit: "Ziyaretinizi Rezerve Edin",
      availableIn: "Mevcut diller:",
      langRussian: "Rusça",
      langTurkish: "Türkçe",
      langIndonesian: "Endonezce",
      langUrdu: "Urduca",
      langFrench: "Fransızca",
      langEnglish: "İngilizce",
      langArabic: "Arapça",
    },
    wings: {
      sectionTitle: "Müze Kanatları",
      sectionDescription: "14 kanat boyunca ruhani ve tarihi bir yolculuk, her biri iman ve İslam tarihinden benzersiz bir hikâye anlatır",
      statWings: "Farklı Kanat",
      statMaterials: "Bilimsel Materyal",
      statExperience: "Ruhani Deneyim",
      moreWings: "Daha Fazla Kanat",
      showing: "Gösterilen",
      of: "/",
      wing: "kanat",
      exploreWing: "Kanadı Keşfet",
      prev: "Önceki",
      next: "Sonraki",
      goTo: "Git",
      wing1Title: "Allah'a Hamdler, Azze ve Celle",
      wing1Desc: "Allah'ın isimleri, sıfatları ve kudretinin delillerinin 100.000 materyal ve konudan derlenen kapsamlı tanıtımı.",
      wing2Title: "Hz. Peygamber'in ﷺ Eşyaları ve Mülkleri",
      wing2Desc: "Hz. Peygamber'in ﷺ kullandığı mobilya, kap ve eşyaları Sünnet'ten açıklamalarla sunan eşsiz bir deneyim.",
      wing3Title: "Hicret Yolu",
      wing3Desc: "Hz. Peygamber'in ﷺ Medine'ye göç yolunun ve yol boyunca yaşanan önemli olayların sunumu.",
      wing4Title: "Hz. Peygamber ﷺ ve Kadınlar",
      wing4Desc: "Hz. Peygamber ﷺ döneminde kadınların statüsünü 350'den fazla onurlandırmayla öne çıkaran kapsamlı sunum.",
      wing5Title: "Hz. Peygamber ﷺ ve Çocuklar",
      wing5Desc: "Çocukların Hz. Peygamber ﷺ ile 250'den fazla övgüye değer etkileşimini sergileyen sunum.",
      wing6Title: "Nebevi Tıp Çadırı",
      wing6Desc: "Kur'an ve Sünnet'te bahsedilen hastalıklar, tedaviler ve faydalı gıdalar hakkında bilimsel sergi.",
      wing7Title: "Hz. Peygamber'in ﷺ Faziletleri ve Özellikleri",
      wing7Desc: "Hz. Peygamber'in ﷺ isimleri, sıfatları, giysileri, yiyecekleri ve görünüşü hakkında detaylar.",
      wing8Title: "Hz. Peygamber ﷺ ile Birlikteymişsiniz Gibi",
      wing8Desc: "Hz. Peygamber'in ﷺ Mekke ve Medine'deki yaşamının özgün teknolojilerle yaratıcı sunumu.",
      wing9Title: "Hz. Peygamber ﷺ ile Birlikteymişsiniz Gibi (Alternatif)",
      wing9Desc: "Aynı konsept, farklı görsel sunum deneyimi.",
      wing10Title: "Selam Olsun Sana Ey Peygamber ﷺ",
      wing10Desc: "Doğumdan vefata kadar Siyer olaylarının kronolojik özeti.",
      wing11Title: "Şerefli Peygamber Odası",
      wing11Desc: "Şerefli odanın boyutları ve olaylarının ayrıntılı açıklaması.",
      wing12Title: "Hz. Peygamber'i ﷺ Görüyormuşsunuz Gibi",
      wing12Desc: "Hz. Peygamber'in ﷺ hayatı, sıfatları ve kişilik özelliklerinin kapsamlı sunumu.",
      wing13Title: "Peygamberleri Görüyormuşsunuz Gibi",
      wing13Desc: "Peygamberlerin dönemleri, mucizeleri ve ahlakının özgün sunumu.",
      wing14Title: "Ek Kanat",
      wing14Desc: "Tutarlı tasarımla gelecekteki bir kanat için ayrılmıştır.",
    },
    tech: {
      badge: "Yenilikçi Teknolojiler",
      sectionTitle: "Müze Teknolojileri",
      sectionDescription: "Müze deneyiminizi eşsiz ve unutulmaz kılan en son interaktif teknolojileri keşfedin",
      immersiveRooms: "Sürükleyici Odalar",
      atlases3d: "3D Atlaslar",
      hologram: "Hologram",
      ai: "Yapay Zekâ",
      cinemaHalls: "Sinema Salonları",
      interactiveScreens: "İnteraktif Ekranlar",
      interactiveMurals: "İnteraktif Duvar Resimleri",
      models3d: "3D Modeller",
      childrenRooms: "İnteraktif Çocuk Odaları",
      interactiveArtifacts: "İnteraktif Eserler",
      vr: "Sanal Gerçeklik (VR)",
      interactiveModels: "İnteraktif Modeller",
    },
    planVisit: {
      sectionTitle: "Ziyaretinizi Planlayın",
      sectionDescription: "Zengin bir müze deneyimi için bilmeniz gereken her şey",
      feature1Title: "Güvenli ve Emniyetli",
      feature1Desc: "Kişisel bilgilerinizi koruyan şifreli ödeme sistemimiz ile güvenle rezervasyon yapın",
      feature2Title: "Önceden Rezerve Edin",
      feature2Desc: "Müsaitliği garanti altına almak ve kuyrukta beklemekten kaçınmak için tercih ettiğiniz tarih ve saati çevrimiçi olarak ayırtın",
      feature3Title: "Herkes İçin",
      feature3Desc: "İslam mirasını keşfetmek isteyen aileler, öğrenciler, araştırmacılar ve dünyanın dört bir yanından ziyaretçiler için ideal",
    },
    locations: {
      sectionTitle: "Küresel Konumlarımız",
      sectionSubtitle: "Üç kıtadaki dünya standartlarındaki müzelerimizi ziyaret edin",
      sectionQuestion: "Hangi şubeyi ziyaret etmek istersiniz?",
      openNow: "Şimdi Açık",
      ticketsFrom: "Biletler şu fiyattan başlar",
      bookVisit: "Ziyaret rezervasyonu yap",
      visitInfo: "Ziyaret Bilgileri",
      visitInfoDesc: "Ziyaretiniz için bilmeniz gereken her şey",
      whatsIncluded: "Neler Dahil",
      durationTiming: "Süre ve Zamanlama",
      duration: "Süre:",
      workingHours: "Çalışma Saatleri:",
      cancellationPolicy: "İptal Politikası",
      mecca: "Mekke",
      medina: "Medine",
      rabat: "Rabat",
      nouakchott: "Nuakşot",
      dakar: "Dakar",
      countrySA: "Suudi Arabistan",
      countryMorocco: "Fas",
      countryMauritania: "Moritanya",
      countrySenegal: "Senegal",
      addressMecca: "Kral Abdulaziz Vakfı, Saat Kulesi, 2. Kat",
      addressMedina: "Peygamber Mescidi Güney Avlusu, Ravza karşısı",
      addressRabat: "UNESCO Binası",
      addressNouakchott: "Nuakşot Şube Adresi",
      addressDakar: "Dakar Şube Adresi",
      guidedTour: "Tercih ettiğiniz dilde rehberli tur",
      allSections60: "60'tan fazla sergi bölümüne erişim",
      allSections: "Tüm sergi bölümlerine erişim",
      interactiveDisplays3d: "İnteraktif sergiler ve 3D model deneyimi",
      interactiveDisplays: "İnteraktif sergi deneyimi",
      cinemaExperience: "Sinema salonu deneyimi",
      freeGuide: "Ücretsiz müze rehber kitapçığı",
      duration23: "2-3 saat",
      hoursSatThu: "Cumartesi - Perşembe 09:00 - 21:00",
      hoursMonSat: "Pazartesi - Cumartesi 10:00 - 20:00",
      hoursMonSat2: "Pazartesi - Cumartesi 10:00 - 18:00",
      hoursSatThu2: "Cumartesi - Perşembe 09:00 - 18:00",
      closedFri: "Cuma günleri kapalı",
      closedSun: "Pazar günleri kapalı",
      cancel24: "Ziyaretten 24 saat öncesine kadar ücretsiz iptal",
      cancel48: "Ziyaretten 48 saat öncesine kadar ücretsiz iptal",
      noRefund24: "24 saat içinde iptallerde iade yapılmaz",
      noRefund48: "48 saat içinde iptallerde iade yapılmaz",
      reschedule: "Müsaitliğe göre yeniden planlama mümkündür",
    },
    testimonials: {
      sectionTitle: "Ziyaretçilerimiz Ne Diyor",
      sectionDescription: "Dünya genelinden ziyaretçi deneyimlerini keşfedin",
      pages: "sayfa",
      of: "/",
      t1text: "Kesinlikle nefes kesici bir deneyim! Sürükleyici sergiler ve tarihi modeller Hz. Peygamber'in ﷺ hayatını canlandırdı. İslam mirasını anlamak isteyen herkes için mutlaka görülmeli.",
      t1highlight: "Kesinlikle nefes kesici bir deneyim!",
      t1name: "Fatima Hassan",
      t1location: "Mekke Şubesini ziyaret etti",
      t2text: "İnteraktif teknoloji ve güzel sergiler, İslam medeniyeti hakkında öğrenmeyi tüm ailemiz için ilgi çekici hale getirdi. Çocuklar özellikle 3D şehir modellerine hayran kaldı.",
      t2highlight: "İnteraktif teknoloji ve güzel sergiler",
      t2name: "Ahmed Al-Rashed",
      t2location: "Medine Şubesini ziyaret etti",
      t3text: "Modern teknolojiyi tarih saygısıyla birleştiren dünya standartlarında bir müze. Çok dilli turlar mükemmeldi ve personel bilgili ve çok misafirperverdi.",
      t3highlight: "Dünya standartlarında bir müze",
      t3name: "Mohammed Benzema",
      t3location: "Rabat Şubesini ziyaret etti",
      t4text: "Unutulmaz bir ruhani ziyaret! Hz. Peygamber'in ﷺ Sîresine daha önce hayal edemeyeceğim bir şekilde yakınlık hissettim. Mekân huzur ve imanla dolu.",
      t4highlight: "Unutulmaz bir ruhani ziyaret!",
      t4name: "Aisha Al-Mansoori",
      t4location: "Dubai Şubesini ziyaret etti",
      t5text: "Şimdiye kadar yaşadığım en iyi kültürel deneyim. Her kanattaki titiz detaylar bu müzenin ne kadar özenle yapıldığını gösteriyor.",
      t5highlight: "Şimdiye kadar yaşadığım en iyi kültürel deneyim.",
      t5name: "Khalid Al-Otaibi",
      t5location: "Cidde Şubesini ziyaret etti",
      t6text: "Ailemi bir tura çıkardım ve çok mutlu oldular. Tasarım her yaşa hitap ediyor ve bilgiyi akıcı ve etkili bir şekilde sunuyor.",
      t6highlight: "Tasarım her yaşa hitap ediyor",
      t6name: "Sara Al-Qahtani",
      t6location: "Riyad Şubesini ziyaret etti",
      t7text: "Çocuklar ve yetişkinler için harika bir eğitim deneyimi. Her aileye bu müzeyi ziyaret etmesini tavsiye ederim.",
      t7highlight: "Harika bir eğitim deneyimi",
      t7name: "Youssef Al-Harbi",
      t7location: "Dammam Şubesini ziyaret etti",
      t8text: "Müze, Hz. Peygamber'in Sîresini muhteşem bir şekilde somutlaştırıyor. Zengin İslam tarihimizle gurur duyarak ayrıldım.",
      t8highlight: "Müze, Hz. Peygamber'in Sîresini muhteşem bir şekilde somutlaştırıyor.",
      t8name: "Noura Al-Subaie",
      t8location: "Kuveyt Şubesini ziyaret etti",
    },
    footer: {
      description: "İslam mirasını kutlayan ve Hz. Peygamber'in ﷺ hikâyesini en son teknolojiler ve interaktif sergilerle anlatan küresel bir müze.",
      quickLinks: "Hızlı Bağlantılar",
      home: "Ana Sayfa",
      aboutMuseum: "Müze Hakkında",
      exhibitions: "Sergiler",
      events: "Etkinlikler",
      contactUs: "Bize Ulaşın",
      branches: "Şubelerimiz",
      branchMecca: "Mekke Şubesi",
      branchMedina: "Medine Şubesi",
      branchRabat: "Rabat Şubesi",
      branchNouakchott: "Nuakşot Şubesi",
      branchDakar: "Dakar Şubesi",
      contactTitle: "Bize Ulaşın",
      address: "Mekke, Suudi Arabistan",
      copyright: "© 2024 Siyer Müzesi. Tüm hakları saklıdır.",
      privacy: "Gizlilik Politikası",
      terms: "Şartlar ve Koşullar",
    },
  },
};
