import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "ar" | "en" | "fr" | "tr" | "ru" | "ur" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar");

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    document.documentElement.dir = (lang === "ar" || lang === "ur") ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, []);

  const t = useCallback(
    (key: string) => {
      const keys = key.split(".");
      let value: any = translations[language];
      for (const k of keys) {
        value = value?.[k];
      }
      return (value as string) ?? key;
    },
    [language]
  );

  const dir = (language === "ar" || language === "ur") ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations: Record<Language, Record<string, any>> = {
  ar: {
    nav: {
      home: "الرئيسية",
      wings: "أجنحة المتحف",
      locations: "المواقع",
      testimonials: "آراء العملاء",
      bookTicket: "احجز تذكرتك",
    },
    hero: {
      badge: "السيرة كأنك تعيشها",
      titleLine1: "المتحف الدولي",
      titleLine2: "للسيرة النبوية",
      description: "اختبر الإرث العميق للنبي محمد ﷺ من خلال التكنولوجيا الأصيلة والقصص الغامرة عبر",
      descriptionLine2: "خمسة مواقع مرموقة حول العالم",
      bookVisit: "احجز زيارتك",
      availableIn: "متاح باللغات:",
      langRussian: "الروسية",
      langTurkish: "التركية",
      langIndonesian: "الإندونيسية",
      langUrdu: "الأردية",
      langFrench: "الفرنسية",
      langEnglish: "الإنجليزية",
      langArabic: "العربية",
    },
    wings: {
      sectionTitle: "أجنحة المتحف",
      sectionDescription: "رحلة روحية وتاريخية عبر 14 جناحًا، كل منها يروي قصة فريدة من قصص الإيمان والتاريخ الإسلامي",
      statWings: "جناح متميز",
      statMaterials: "مادة علمية",
      statExperience: "تجربة روحية",
      moreWings: "المزيد من الأجنحة",
      showing: "عرض",
      of: "من",
      wing: "جناح",
      exploreWing: "استكشف الجناح",
      prev: "السابق",
      next: "التالي",
      goTo: "الانتقال إلى",
      wing1Title: "التحيات لله، عزَّ وجلَّ",
      wing1Desc: "تعريف شامل بالله وأسمائه وصفاته ودلائل قدرته، مستخلص من مئة ألف مادة وموضوع.",
      wing2Title: "أثاث النبي ﷺ ومقتنياته",
      wing2Desc: "تجربة فريدة تعرض كل ما استخدمه النبي ﷺ من أثاث وأوانٍ ومقتنيات مع تعريف بها وما ورد عنها في السنة.",
      wing3Title: "طريق الهجرة",
      wing3Desc: "عرض لمسار هجرة النبي ﷺ إلى المدينة وأهم المواقف التي مر بها.",
      wing4Title: "النبي ﷺ والمرأة",
      wing4Desc: "عرض شامل يبرز مكانة المرأة في زمن النبي ﷺ ولائحة شرف تضم أكثر من 350 تشريفًا.",
      wing5Title: "النبي ﷺ والطفل",
      wing5Desc: "عرض يُظهر أكثر من 250 موقفًا محمودًا للأطفال مع النبي ﷺ.",
      wing6Title: "خيمة الطب النبوي",
      wing6Desc: "عرض علمي لما ورد في القرآن والسنة عن الأمراض والعلاج والأطعمة المفيدة.",
      wing7Title: "فضائل النبي ﷺ وشمائله",
      wing7Desc: "تفاصيل عن أسماء النبي ﷺ وصفاته ولباسه وطعامه وهيئته.",
      wing8Title: "النبي ﷺ كأنك معه",
      wing8Desc: "عرض إبداعي لحياة النبي ﷺ في مكة والمدينة باستخدام تقنيات مميزة.",
      wing9Title: "النبي ﷺ كأنك معه (نسخة مختلفة)",
      wing9Desc: "نفس الفكرة لكن بتجربة عرض مختلفة بصريًا.",
      wing10Title: "السلام عليك أيها النبي ﷺ",
      wing10Desc: "تلخيص زمني لأحداث السيرة النبوية من الميلاد حتى الوفاة.",
      wing11Title: "الحجرة النبوية الشريفة",
      wing11Desc: "وصف دقيق للحجرة الشريفة ومساحتها وأحداثها.",
      wing12Title: "النبي ﷺ كأنك تراه",
      wing12Desc: "عرض شامل لحياة النبي ﷺ وصفاته ومعالم شخصيته.",
      wing13Title: "الأنبياء كأنك تراهم",
      wing13Desc: "عرض مميز للأنبياء، أزمانهم، معجزاتهم، وآدابهم.",
      wing14Title: "جناح إضافي",
      wing14Desc: "يُترك بتصميم متناسق لعرض جناح مستقبلي.",
    },
    tech: {
      badge: "تقنيات مبتكرة",
      sectionTitle: "تقنيات المتحف",
      sectionDescription: "اكتشف أحدث التقنيات التفاعلية التي تجعل تجربتك في المتحف فريدة ومميزة",
      immersiveRooms: "الغرف الانغماسية",
      atlases3d: "الأطالس ثلاثية الأبعاد",
      hologram: "الهولوجرام",
      ai: "الذكاء الاصطناعي",
      cinemaHalls: "قاعات السينما",
      interactiveScreens: "الشاشات التفاعلية",
      interactiveMurals: "الجداريات التفاعلية",
      models3d: "المجسمات ثلاثية الأبعاد",
      childrenRooms: "غرف تفاعلية للأطفال",
      interactiveArtifacts: "المقتنيات التفاعلية",
      vr: "الواقع الافتراضي",
      interactiveModels: "النماذج التفاعلية",
    },
    planVisit: {
      sectionTitle: "خطط زيارتك",
      sectionDescription: "كل ما تحتاج معرفته لتجربة متحف غنية",
      feature1Title: "آمن ومضمون",
      feature1Desc: "احجز بثقة من خلال نظام الدفع المشفر الذي يحمي معلوماتك الشخصية",
      feature2Title: "احجز مسبقاً",
      feature2Desc: "احجز التاريخ والوقت المفضل لديك عبر الإنترنت لضمان التوفر وتجنب الانتظار في الطوابير",
      feature3Title: "للجميع",
      feature3Desc: "مثالي للعائلات والطلاب والباحثين والزوار من جميع أنحاء العالم الذين يسعون لاستكشاف التراث الإسلامي",
    },
    locations: {
      sectionTitle: "مواقعنا العالمية",
      sectionSubtitle: "قم بزيارة متاحفنا ذات المستوى العالمي في ثلاث قارات",
      sectionQuestion: "أي فرع ترغب في زيارته؟",
      openNow: "مفتوح الآن",
      ticketsFrom: "تبدأ التذاكر من",
      bookVisit: "احجز زيارة",
      visitInfo: "معلومات الزيارة",
      visitInfoDesc: "كل ما تحتاج معرفته لزيارتك",
      whatsIncluded: "ما يشمله",
      durationTiming: "المدة والتوقيت",
      duration: "المدة:",
      workingHours: "ساعات العمل:",
      cancellationPolicy: "سياسة الإلغاء",
      mecca: "مكة المكرمة",
      medina: "المدينة المنورة",
      rabat: "الرباط",
      nouakchott: "نواكشوط",
      dakar: "داكار",
      countrySA: "المملكة العربية السعودية",
      countryMorocco: "المملكة المغربية",
      countryMauritania: "موريتانيا",
      countrySenegal: "السنغال",
      addressMecca: "وقف الملك عبدالعزيز رحمه الله برج الساعة الدور الثاني",
      addressMedina: "الساحة الجنوبية للمسجد النبوي الشريف مقابل الروضة",
      addressRabat: "مبنى اليونيسكو",
      addressNouakchott: "أدخل عنوان فرع نواكشوط هنا",
      addressDakar: "أدخل عنوان فرع داكار هنا",
      guidedTour: "جولة إرشادية باللغة التي تفضلها",
      allSections60: "الدخول إلى جميع أقسام المعرض الـ 60+",
      allSections: "الدخول إلى جميع أقسام المعرض",
      interactiveDisplays3d: "تجربة العروض التفاعلية والنماذج ثلاثية الأبعاد",
      interactiveDisplays: "تجربة العروض التفاعلية",
      cinemaExperience: "تجربة قاعة السينما",
      freeGuide: "كتيب إرشادي مجاني للمتحف",
      duration23: "2-3 ساعات",
      hoursSatThu: "السبت - الخميس 9:00 صباحاً - 9:00 مساءً",
      hoursMonSat: "الإثنين - السبت 10:00 صباحاً - 8:00 مساءً",
      hoursMonSat2: "الإثنين - السبت 10:00 صباحاً - 6:00 مساءً",
      hoursSatThu2: "السبت - الخميس 9:00 صباحاً - 6:00 مساءً",
      closedFri: "مغلق أيام الجمعة",
      closedSun: "مغلق أيام الأحد",
      cancel24: "إلغاء مجاني قبل 24 ساعة من موعد الزيارة",
      cancel48: "إلغاء مجاني قبل 48 ساعة من موعد الزيارة",
      noRefund24: "لا يوجد استرداد للإلغاء خلال 24 ساعة",
      noRefund48: "لا يوجد استرداد للإلغاء خلال 48 ساعة",
      reschedule: "إعادة الجدولة متاحة حسب التوفر",
    },
    testimonials: {
      sectionTitle: "ماذا يقول زوارنا",
      sectionDescription: "اكتشف تجارب الزوار من جميع أنحاء العالم",
      pages: "صفحات",
      of: "من",
      t1text: "تجربة خلابة تماماً! العروض الغامرة والنماذج التاريخية أحيت حياة الرسول ﷺ بشكل واقعي. يجب زيارتها لأي شخص يسعى لفهم التراث الإسلامي.",
      t1highlight: "تجربة خلابة تماماً!",
      t1name: "فاطمة حسن",
      t1location: "زارت فرع مكة المكرمة",
      t2text: "التقنية التفاعلية والمعروضات الجميلة جعلت التعلم عن الحضارة الإسلامية جذاباً لعائلتنا بأكملها. كان الأطفال مفتونين بشكل خاص بنماذج المدن ثلاثية الأبعاد.",
      t2highlight: "التقنية التفاعلية والمعروضات الجميلة",
      t2name: "أحمد الراشد",
      t2location: "زار فرع المدينة المنورة",
      t3text: "متحف عالمي المستوى يجمع بين التكنولوجيا الحديثة والاحترام العميق للتاريخ. كانت الجولات متعددة اللغات ممتازة، والموظفون كانوا ذوي معرفة واسعة ومرحبين للغاية.",
      t3highlight: "متحف عالمي المستوى",
      t3name: "محمد بنزيمة",
      t3location: "زار فرع الرباط",
      t4text: "زيارة روحانية لا تُنسى! شعرت بالقرب من سيرة النبي ﷺ بطريقة لم أتخيلها من قبل. المكان يفيض بالسكينة والإيمان.",
      t4highlight: "زيارة روحانية لا تُنسى!",
      t4name: "عائشة المنصوري",
      t4location: "زارت فرع دبي",
      t5text: "أفضل تجربة ثقافية مررت بها. التفاصيل الدقيقة في كل جناح تظهر مدى الاهتمام والحب الذي بُني به هذا المتحف.",
      t5highlight: "أفضل تجربة ثقافية مررت بها.",
      t5name: "خالد العتيبي",
      t5location: "زار فرع جدة",
      t6text: "أخذت والديّ في جولة وكانا سعيدين جداً. التصميم يراعي جميع الأعمار ويقدم المعلومات بأسلوب سلس ومؤثر.",
      t6highlight: "التصميم يراعي جميع الأعمار",
      t6name: "سارة القحطاني",
      t6location: "زارت فرع الرياض",
      t7text: "تجربة تعليمية رائعة للأطفال والكبار على حد سواء. أنصح كل عائلة بزيارة هذا المتحف.",
      t7highlight: "تجربة تعليمية رائعة",
      t7name: "يوسف الحربي",
      t7location: "زار فرع الدمام",
      t8text: "المتحف يجسد السيرة النبوية بشكل مبهر. خرجت وأنا أشعر بالفخر بتاريخنا الإسلامي العريق.",
      t8highlight: "المتحف يجسد السيرة النبوية بشكل مبهر.",
      t8name: "نورة السبيعي",
      t8location: "زارت فرع الكويت",
    },
    footer: {
      description: "متحف عالمي يحتفي بالتراث الإسلامي ويروي قصة الرسول ﷺ من خلال أحدث التقنيات والمعروضات التفاعلية.",
      quickLinks: "روابط سريعة",
      home: "الرئيسية",
      aboutMuseum: "عن المتحف",
      exhibitions: "المعارض",
      events: "الفعاليات",
      contactUs: "تواصل معنا",
      branches: "فروعنا",
      branchMecca: "فرع مكة المكرمة",
      branchMedina: "فرع المدينة المنورة",
      branchRabat: "فرع الرباط",
      branchNouakchott: "فرع نواكشوط",
      branchDakar: "فرع داكار",
      contactTitle: "تواصل معنا",
      address: "مكة المكرمة، المملكة العربية السعودية",
      copyright: "© 2024 متحف السيرة النبوية. جميع الحقوق محفوظة.",
      privacy: "سياسة الخصوصية",
      terms: "الشروط والأحكام",
    },
  },
  en: {
    nav: {
      home: "Home",
      wings: "Museum Wings",
      locations: "Locations",
      technologies: "Technologies",
      planVisit: "Plan Your Visit",
      bookTicket: "Book Ticket",
    },
    hero: {
      badge: "Experience the Seerah",
      titleLine1: "The International",
      titleLine2: "Seerah Museum",
      description: "Experience the profound legacy of Prophet Muhammad ﷺ through authentic technology and immersive storytelling across",
      descriptionLine2: "five prestigious locations worldwide",
      bookVisit: "Book Your Visit",
      availableIn: "Available in:",
      langRussian: "Russian",
      langTurkish: "Turkish",
      langIndonesian: "Indonesian",
      langUrdu: "Urdu",
      langFrench: "French",
      langEnglish: "English",
      langArabic: "Arabic",
    },
    wings: {
      sectionTitle: "Museum Wings",
      sectionDescription: "A spiritual and historical journey through 14 wings, each telling a unique story of faith and Islamic history",
      statWings: "Distinct Wings",
      statMaterials: "Scientific Materials",
      statExperience: "Spiritual Experience",
      moreWings: "More Wings",
      showing: "Showing",
      of: "of",
      wing: "wings",
      exploreWing: "Explore Wing",
      prev: "Previous",
      next: "Next",
      goTo: "Go to",
      wing1Title: "Praises to Allah, the Almighty",
      wing1Desc: "A comprehensive introduction to Allah, His names, attributes, and signs of His power, drawn from 100,000 materials and topics.",
      wing2Title: "The Prophet's ﷺ Furnishings & Belongings",
      wing2Desc: "A unique experience showcasing everything used by the Prophet ﷺ including furniture, vessels, and belongings with descriptions from the Sunnah.",
      wing3Title: "The Hijrah Route",
      wing3Desc: "A display of the Prophet's ﷺ migration path to Medina and the key events along the way.",
      wing4Title: "The Prophet ﷺ and Women",
      wing4Desc: "A comprehensive display highlighting women's status during the Prophet's ﷺ era with an honor list of over 350 recognitions.",
      wing5Title: "The Prophet ﷺ and Children",
      wing5Desc: "A display showcasing over 250 praiseworthy interactions of children with the Prophet ﷺ.",
      wing6Title: "Prophetic Medicine Tent",
      wing6Desc: "A scientific exhibition on diseases, treatments, and beneficial foods mentioned in the Quran and Sunnah.",
      wing7Title: "Virtues & Characteristics of the Prophet ﷺ",
      wing7Desc: "Details about the Prophet's ﷺ names, attributes, clothing, food, and appearance.",
      wing8Title: "As If You Were With the Prophet ﷺ",
      wing8Desc: "A creative display of the Prophet's ﷺ life in Mecca and Medina using distinctive technologies.",
      wing9Title: "As If You Were With the Prophet ﷺ (Alternate)",
      wing9Desc: "Same concept with a different visual presentation experience.",
      wing10Title: "Peace Be Upon You, O Prophet ﷺ",
      wing10Desc: "A chronological summary of Seerah events from birth to passing.",
      wing11Title: "The Noble Prophet's Chamber",
      wing11Desc: "A precise description of the noble chamber, its dimensions, and events.",
      wing12Title: "The Prophet ﷺ As If You See Him",
      wing12Desc: "A comprehensive display of the Prophet's ﷺ life, attributes, and personality traits.",
      wing13Title: "The Prophets As If You See Them",
      wing13Desc: "A distinctive display of the prophets, their eras, miracles, and manners.",
      wing14Title: "Additional Wing",
      wing14Desc: "Reserved for a future wing with consistent design.",
    },
    tech: {
      badge: "Innovative Technologies",
      sectionTitle: "Museum Technologies",
      sectionDescription: "Discover the latest interactive technologies that make your museum experience unique and memorable",
      immersiveRooms: "Immersive Rooms",
      atlases3d: "3D Atlases",
      hologram: "Hologram",
      ai: "Artificial Intelligence",
      cinemaHalls: "Cinema Halls",
      interactiveScreens: "Interactive Screens",
      interactiveMurals: "Interactive Murals",
      models3d: "3D Models",
      childrenRooms: "Interactive Children's Rooms",
      interactiveArtifacts: "Interactive Artifacts",
      vr: "Virtual Reality (VR)",
      interactiveModels: "Interactive Models",
    },
    planVisit: {
      sectionTitle: "Plan Your Visit",
      sectionDescription: "Everything you need to know for a rich museum experience",
      feature1Title: "Safe & Secure",
      feature1Desc: "Book with confidence through our encrypted payment system that protects your personal information",
      feature2Title: "Book in Advance",
      feature2Desc: "Reserve your preferred date and time online to ensure availability and avoid waiting in queues",
      feature3Title: "For Everyone",
      feature3Desc: "Perfect for families, students, researchers, and visitors from around the world seeking to explore Islamic heritage",
    },
    locations: {
      sectionTitle: "Our Global Locations",
      sectionSubtitle: "Visit our world-class museums across three continents",
      sectionQuestion: "Which branch would you like to visit?",
      openNow: "Open Now",
      ticketsFrom: "Tickets start from",
      bookVisit: "Book a visit to",
      visitInfo: "Visit Information",
      visitInfoDesc: "Everything you need to know for your visit",
      whatsIncluded: "What's Included",
      durationTiming: "Duration & Timing",
      duration: "Duration:",
      workingHours: "Working Hours:",
      cancellationPolicy: "Cancellation Policy",
      mecca: "Makkah",
      medina: "Madinah",
      rabat: "Rabat",
      nouakchott: "Nouakchott",
      dakar: "Dakar",
      countrySA: "Saudi Arabia",
      countryMorocco: "Morocco",
      countryMauritania: "Mauritania",
      countrySenegal: "Senegal",
      addressMecca: "King Abdulaziz Endowment, Clock Tower, 2nd Floor",
      addressMedina: "South Courtyard of the Prophet's Mosque, opposite Al-Rawdah",
      addressRabat: "UNESCO Building",
      addressNouakchott: "Nouakchott Branch Address",
      addressDakar: "Dakar Branch Address",
      guidedTour: "Guided tour in your preferred language",
      allSections60: "Access to all 60+ exhibition sections",
      allSections: "Access to all exhibition sections",
      interactiveDisplays3d: "Interactive displays and 3D models experience",
      interactiveDisplays: "Interactive displays experience",
      cinemaExperience: "Cinema hall experience",
      freeGuide: "Free museum guidebook",
      duration23: "2-3 hours",
      hoursSatThu: "Saturday - Thursday 9:00 AM - 9:00 PM",
      hoursMonSat: "Monday - Saturday 10:00 AM - 8:00 PM",
      hoursMonSat2: "Monday - Saturday 10:00 AM - 6:00 PM",
      hoursSatThu2: "Saturday - Thursday 9:00 AM - 6:00 PM",
      closedFri: "Closed on Fridays",
      closedSun: "Closed on Sundays",
      cancel24: "Free cancellation up to 24 hours before visit",
      cancel48: "Free cancellation up to 48 hours before visit",
      noRefund24: "No refund for cancellation within 24 hours",
      noRefund48: "No refund for cancellation within 48 hours",
      reschedule: "Rescheduling available based on availability",
    },
    testimonials: {
      sectionTitle: "What Our Visitors Say",
      sectionDescription: "Discover experiences from visitors around the world",
      pages: "pages",
      of: "of",
      t1text: "An absolutely breathtaking experience! The immersive displays and historical models brought the life of the Prophet ﷺ to life. A must-visit for anyone seeking to understand Islamic heritage.",
      t1highlight: "An absolutely breathtaking experience!",
      t1name: "Fatima Hassan",
      t1location: "Visited Makkah Branch",
      t2text: "The interactive technology and beautiful exhibits made learning about Islamic civilization engaging for our entire family. The children were especially fascinated by the 3D city models.",
      t2highlight: "The interactive technology and beautiful exhibits",
      t2name: "Ahmed Al-Rashed",
      t2location: "Visited Madinah Branch",
      t3text: "A world-class museum that combines modern technology with deep respect for history. The multilingual tours were excellent, and the staff were knowledgeable and very welcoming.",
      t3highlight: "A world-class museum",
      t3name: "Mohammed Benzema",
      t3location: "Visited Rabat Branch",
      t4text: "An unforgettable spiritual visit! I felt close to the Prophet's ﷺ Seerah in a way I never imagined before. The place overflows with tranquility and faith.",
      t4highlight: "An unforgettable spiritual visit!",
      t4name: "Aisha Al-Mansoori",
      t4location: "Visited Dubai Branch",
      t5text: "The best cultural experience I've ever had. The meticulous details in every wing show the care and love with which this museum was built.",
      t5highlight: "The best cultural experience I've ever had.",
      t5name: "Khalid Al-Otaibi",
      t5location: "Visited Jeddah Branch",
      t6text: "I took my parents on a tour and they were so happy. The design caters to all ages and presents information in a smooth and impactful way.",
      t6highlight: "The design caters to all ages",
      t6name: "Sara Al-Qahtani",
      t6location: "Visited Riyadh Branch",
      t7text: "A wonderful educational experience for children and adults alike. I recommend every family visit this museum.",
      t7highlight: "A wonderful educational experience",
      t7name: "Youssef Al-Harbi",
      t7location: "Visited Dammam Branch",
      t8text: "The museum embodies the Prophet's Seerah magnificently. I left feeling proud of our rich Islamic history.",
      t8highlight: "The museum embodies the Prophet's Seerah magnificently.",
      t8name: "Noura Al-Subaie",
      t8location: "Visited Kuwait Branch",
    },
    footer: {
      description: "A global museum celebrating Islamic heritage and telling the story of the Prophet ﷺ through the latest technologies and interactive exhibits.",
      quickLinks: "Quick Links",
      home: "Home",
      aboutMuseum: "About the Museum",
      exhibitions: "Exhibitions",
      events: "Events",
      contactUs: "Contact Us",
      branches: "Our Branches",
      branchMecca: "Makkah Branch",
      branchMedina: "Madinah Branch",
      branchRabat: "Rabat Branch",
      branchNouakchott: "Nouakchott Branch",
      branchDakar: "Dakar Branch",
      contactTitle: "Contact Us",
      address: "Makkah, Saudi Arabia",
      copyright: "© 2024 Seerah Museum. All rights reserved.",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
    },
  },
  fr: {
    nav: {
      home: "Accueil",
      wings: "Ailes du Musée",
      locations: "Emplacements",
      technologies: "Technologies",
      planVisit: "Planifiez Votre Visite",
      bookTicket: "Réserver un Billet",
    },
    hero: {
      badge: "Vivez la Sîra",
      titleLine1: "Le Musée International",
      titleLine2: "de la Sîra du Prophète",
      description: "Découvrez l'héritage profond du Prophète Muhammad ﷺ à travers des technologies authentiques et des récits immersifs dans",
      descriptionLine2: "cinq sites prestigieux à travers le monde",
      bookVisit: "Réservez Votre Visite",
      availableIn: "Disponible en :",
      langRussian: "Russe",
      langTurkish: "Turc",
      langIndonesian: "Indonésien",
      langUrdu: "Ourdou",
      langFrench: "Français",
      langEnglish: "Anglais",
      langArabic: "Arabe",
    },
    wings: {
      sectionTitle: "Ailes du Musée",
      sectionDescription: "Un voyage spirituel et historique à travers 14 ailes, chacune racontant une histoire unique de foi et d'histoire islamique",
      statWings: "Ailes Distinctes",
      statMaterials: "Matériaux Scientifiques",
      statExperience: "Expérience Spirituelle",
      moreWings: "Plus d'Ailes",
      showing: "Affichage",
      of: "de",
      wing: "ailes",
      exploreWing: "Explorer l'Aile",
      prev: "Précédent",
      next: "Suivant",
      goTo: "Aller à",
      wing1Title: "Louanges à Allah, le Tout-Puissant",
      wing1Desc: "Une introduction complète à Allah, Ses noms, attributs et signes de Sa puissance, tirée de 100 000 matériaux et sujets.",
      wing2Title: "Mobilier et Effets du Prophète ﷺ",
      wing2Desc: "Une expérience unique présentant tout ce que le Prophète ﷺ a utilisé, y compris meubles, récipients et effets personnels avec des descriptions de la Sunna.",
      wing3Title: "La Route de la Hijra",
      wing3Desc: "Une présentation du chemin de migration du Prophète ﷺ vers Médine et les événements clés en chemin.",
      wing4Title: "Le Prophète ﷺ et les Femmes",
      wing4Desc: "Une présentation complète mettant en lumière le statut des femmes à l'époque du Prophète ﷺ avec une liste d'honneur de plus de 350 reconnaissances.",
      wing5Title: "Le Prophète ﷺ et les Enfants",
      wing5Desc: "Une présentation de plus de 250 interactions louables des enfants avec le Prophète ﷺ.",
      wing6Title: "Tente de Médecine Prophétique",
      wing6Desc: "Une exposition scientifique sur les maladies, traitements et aliments bénéfiques mentionnés dans le Coran et la Sunna.",
      wing7Title: "Vertus et Caractéristiques du Prophète ﷺ",
      wing7Desc: "Détails sur les noms, attributs, vêtements, nourriture et apparence du Prophète ﷺ.",
      wing8Title: "Comme Si Vous Étiez Avec le Prophète ﷺ",
      wing8Desc: "Une présentation créative de la vie du Prophète ﷺ à La Mecque et Médine utilisant des technologies distinctives.",
      wing9Title: "Comme Si Vous Étiez Avec le Prophète ﷺ (Alternatif)",
      wing9Desc: "Même concept avec une expérience de présentation visuelle différente.",
      wing10Title: "Paix Sur Vous, Ô Prophète ﷺ",
      wing10Desc: "Un résumé chronologique des événements de la Sîra de la naissance au décès.",
      wing11Title: "La Noble Chambre du Prophète",
      wing11Desc: "Une description précise de la noble chambre, ses dimensions et événements.",
      wing12Title: "Le Prophète ﷺ Comme Si Vous Le Voyez",
      wing12Desc: "Une présentation complète de la vie, des attributs et des traits de personnalité du Prophète ﷺ.",
      wing13Title: "Les Prophètes Comme Si Vous Les Voyez",
      wing13Desc: "Une présentation distinctive des prophètes, leurs époques, miracles et manières.",
      wing14Title: "Aile Supplémentaire",
      wing14Desc: "Réservée pour une future aile avec un design cohérent.",
    },
    tech: {
      badge: "Technologies Innovantes",
      sectionTitle: "Technologies du Musée",
      sectionDescription: "Découvrez les dernières technologies interactives qui rendent votre expérience muséale unique et mémorable",
      immersiveRooms: "Salles Immersives",
      atlases3d: "Atlas 3D",
      hologram: "Hologramme",
      ai: "Intelligence Artificielle",
      cinemaHalls: "Salles de Cinéma",
      interactiveScreens: "Écrans Interactifs",
      interactiveMurals: "Fresques Interactives",
      models3d: "Modèles 3D",
      childrenRooms: "Salles Interactives pour Enfants",
      interactiveArtifacts: "Artefacts Interactifs",
      vr: "Réalité Virtuelle (VR)",
      interactiveModels: "Modèles Interactifs",
    },
    planVisit: {
      sectionTitle: "Planifiez Votre Visite",
      sectionDescription: "Tout ce que vous devez savoir pour une expérience muséale enrichissante",
      feature1Title: "Sûr et Sécurisé",
      feature1Desc: "Réservez en toute confiance grâce à notre système de paiement chiffré qui protège vos informations personnelles",
      feature2Title: "Réservez à l'Avance",
      feature2Desc: "Réservez votre date et heure préférées en ligne pour garantir la disponibilité et éviter les files d'attente",
      feature3Title: "Pour Tous",
      feature3Desc: "Parfait pour les familles, étudiants, chercheurs et visiteurs du monde entier souhaitant explorer le patrimoine islamique",
    },
    locations: {
      sectionTitle: "Nos Sites Mondiaux",
      sectionSubtitle: "Visitez nos musées de classe mondiale sur trois continents",
      sectionQuestion: "Quelle branche souhaitez-vous visiter ?",
      openNow: "Ouvert Maintenant",
      ticketsFrom: "Billets à partir de",
      bookVisit: "Réserver une visite à",
      visitInfo: "Informations de Visite",
      visitInfoDesc: "Tout ce que vous devez savoir pour votre visite",
      whatsIncluded: "Ce qui est inclus",
      durationTiming: "Durée et Horaires",
      duration: "Durée :",
      workingHours: "Heures d'ouverture :",
      cancellationPolicy: "Politique d'Annulation",
      mecca: "La Mecque",
      medina: "Médine",
      rabat: "Rabat",
      nouakchott: "Nouakchott",
      dakar: "Dakar",
      countrySA: "Arabie Saoudite",
      countryMorocco: "Maroc",
      countryMauritania: "Mauritanie",
      countrySenegal: "Sénégal",
      addressMecca: "Waqf du Roi Abdulaziz, Tour de l'Horloge, 2e étage",
      addressMedina: "Cour sud de la Mosquée du Prophète, face à Al-Rawdah",
      addressRabat: "Bâtiment UNESCO",
      addressNouakchott: "Adresse de la branche de Nouakchott",
      addressDakar: "Adresse de la branche de Dakar",
      guidedTour: "Visite guidée dans la langue de votre choix",
      allSections60: "Accès à plus de 60 sections d'exposition",
      allSections: "Accès à toutes les sections d'exposition",
      interactiveDisplays3d: "Expérience de présentations interactives et modèles 3D",
      interactiveDisplays: "Expérience de présentations interactives",
      cinemaExperience: "Expérience de la salle de cinéma",
      freeGuide: "Guide gratuit du musée",
      duration23: "2-3 heures",
      hoursSatThu: "Samedi - Jeudi 9h00 - 21h00",
      hoursMonSat: "Lundi - Samedi 10h00 - 20h00",
      hoursMonSat2: "Lundi - Samedi 10h00 - 18h00",
      hoursSatThu2: "Samedi - Jeudi 9h00 - 18h00",
      closedFri: "Fermé le vendredi",
      closedSun: "Fermé le dimanche",
      cancel24: "Annulation gratuite jusqu'à 24 heures avant la visite",
      cancel48: "Annulation gratuite jusqu'à 48 heures avant la visite",
      noRefund24: "Aucun remboursement pour annulation dans les 24 heures",
      noRefund48: "Aucun remboursement pour annulation dans les 48 heures",
      reschedule: "Reprogrammation disponible selon la disponibilité",
    },
    testimonials: {
      sectionTitle: "Ce que Disent Nos Visiteurs",
      sectionDescription: "Découvrez les expériences de visiteurs du monde entier",
      pages: "pages",
      of: "de",
      t1text: "Une expérience absolument époustouflante ! Les présentations immersives et les modèles historiques ont donné vie à la vie du Prophète ﷺ. Un incontournable pour quiconque cherche à comprendre le patrimoine islamique.",
      t1highlight: "Une expérience absolument époustouflante !",
      t1name: "Fatima Hassan",
      t1location: "A visité la branche de La Mecque",
      t2text: "La technologie interactive et les belles expositions ont rendu l'apprentissage de la civilisation islamique captivant pour toute notre famille. Les enfants étaient particulièrement fascinés par les modèles 3D des villes.",
      t2highlight: "La technologie interactive et les belles expositions",
      t2name: "Ahmed Al-Rashed",
      t2location: "A visité la branche de Médine",
      t3text: "Un musée de classe mondiale qui allie technologie moderne et profond respect de l'histoire. Les visites multilingues étaient excellentes et le personnel était compétent et très accueillant.",
      t3highlight: "Un musée de classe mondiale",
      t3name: "Mohammed Benzema",
      t3location: "A visité la branche de Rabat",
      t4text: "Une visite spirituelle inoubliable ! Je me suis senti proche de la Sîra du Prophète ﷺ d'une manière que je n'avais jamais imaginée. Le lieu déborde de sérénité et de foi.",
      t4highlight: "Une visite spirituelle inoubliable !",
      t4name: "Aisha Al-Mansoori",
      t4location: "A visité la branche de Dubaï",
      t5text: "La meilleure expérience culturelle que j'aie jamais eue. Les détails minutieux dans chaque aile montrent le soin et l'amour avec lesquels ce musée a été construit.",
      t5highlight: "La meilleure expérience culturelle que j'aie jamais eue.",
      t5name: "Khalid Al-Otaibi",
      t5location: "A visité la branche de Djeddah",
      t6text: "J'ai emmené mes parents en visite et ils étaient très heureux. Le design convient à tous les âges et présente les informations de manière fluide et percutante.",
      t6highlight: "Le design convient à tous les âges",
      t6name: "Sara Al-Qahtani",
      t6location: "A visité la branche de Riyad",
      t7text: "Une merveilleuse expérience éducative pour les enfants et les adultes. Je recommande à chaque famille de visiter ce musée.",
      t7highlight: "Une merveilleuse expérience éducative",
      t7name: "Youssef Al-Harbi",
      t7location: "A visité la branche de Dammam",
      t8text: "Le musée incarne magnifiquement la Sîra du Prophète. J'en suis ressorti fier de notre riche histoire islamique.",
      t8highlight: "Le musée incarne magnifiquement la Sîra du Prophète.",
      t8name: "Noura Al-Subaie",
      t8location: "A visité la branche du Koweït",
    },
    footer: {
      description: "Un musée mondial célébrant le patrimoine islamique et racontant l'histoire du Prophète ﷺ à travers les dernières technologies et expositions interactives.",
      quickLinks: "Liens Rapides",
      home: "Accueil",
      aboutMuseum: "À Propos du Musée",
      exhibitions: "Expositions",
      events: "Événements",
      contactUs: "Contactez-Nous",
      branches: "Nos Branches",
      branchMecca: "Branche de La Mecque",
      branchMedina: "Branche de Médine",
      branchRabat: "Branche de Rabat",
      branchNouakchott: "Branche de Nouakchott",
      branchDakar: "Branche de Dakar",
      contactTitle: "Contactez-Nous",
      address: "La Mecque, Arabie Saoudite",
      copyright: "© 2024 Musée de la Sîra. Tous droits réservés.",
      privacy: "Politique de Confidentialité",
      terms: "Conditions Générales",
    },
  },
  tr: {
    nav: {
      home: "Ana Sayfa",
      wings: "Müze Kanatları",
      locations: "Konumlar",
      technologies: "Teknolojiler",
      planVisit: "Ziyaretinizi Planlayın",
      bookTicket: "Bilet Al",
    },
    hero: {
      badge: "Sîreyi Yaşayın",
      titleLine1: "Uluslararası",
      titleLine2: "Siyer Müzesi",
      description: "Hz. Muhammed ﷺ'in derin mirasını özgün teknoloji ve sürükleyici hikâye anlatımıyla keşfedin",
      descriptionLine2: "dünya genelinde beş prestijli lokasyonda",
      bookVisit: "Ziyaretinizi Rezerve Edin",
      availableIn: "Mevcut diller:",
      langRussian: "Rusça",
      langTurkish: "Türkçe",
      langIndonesian: "Endonezce",
      langUrdu: "Urduca",
      langFrench: "Fransızca",
      langEnglish: "İngilizce",
      langArabic: "Arapça",
    },
    wings: {
      sectionTitle: "Müze Kanatları",
      sectionDescription: "14 kanat boyunca ruhani ve tarihi bir yolculuk, her biri iman ve İslam tarihinden benzersiz bir hikâye anlatır",
      statWings: "Farklı Kanat",
      statMaterials: "Bilimsel Materyal",
      statExperience: "Ruhani Deneyim",
      moreWings: "Daha Fazla Kanat",
      showing: "Gösterilen",
      of: "/",
      wing: "kanat",
      exploreWing: "Kanadı Keşfet",
      prev: "Önceki",
      next: "Sonraki",
      goTo: "Git",
      wing1Title: "Allah'a Hamdler, Azze ve Celle",
      wing1Desc: "Allah'ın isimleri, sıfatları ve kudretinin delillerinin 100.000 materyal ve konudan derlenen kapsamlı tanıtımı.",
      wing2Title: "Hz. Peygamber'in ﷺ Eşyaları ve Mülkleri",
      wing2Desc: "Hz. Peygamber'in ﷺ kullandığı mobilya, kap ve eşyaları Sünnet'ten açıklamalarla sunan eşsiz bir deneyim.",
      wing3Title: "Hicret Yolu",
      wing3Desc: "Hz. Peygamber'in ﷺ Medine'ye göç yolunun ve yol boyunca yaşanan önemli olayların sunumu.",
      wing4Title: "Hz. Peygamber ﷺ ve Kadınlar",
      wing4Desc: "Hz. Peygamber ﷺ döneminde kadınların statüsünü 350'den fazla onurlandırmayla öne çıkaran kapsamlı sunum.",
      wing5Title: "Hz. Peygamber ﷺ ve Çocuklar",
      wing5Desc: "Çocukların Hz. Peygamber ﷺ ile 250'den fazla övgüye değer etkileşimini sergileyen sunum.",
      wing6Title: "Nebevi Tıp Çadırı",
      wing6Desc: "Kur'an ve Sünnet'te bahsedilen hastalıklar, tedaviler ve faydalı gıdalar hakkında bilimsel sergi.",
      wing7Title: "Hz. Peygamber'in ﷺ Faziletleri ve Özellikleri",
      wing7Desc: "Hz. Peygamber'in ﷺ isimleri, sıfatları, giysileri, yiyecekleri ve görünüşü hakkında detaylar.",
      wing8Title: "Hz. Peygamber ﷺ ile Birlikteymişsiniz Gibi",
      wing8Desc: "Hz. Peygamber'in ﷺ Mekke ve Medine'deki yaşamının özgün teknolojilerle yaratıcı sunumu.",
      wing9Title: "Hz. Peygamber ﷺ ile Birlikteymişsiniz Gibi (Alternatif)",
      wing9Desc: "Aynı konsept, farklı görsel sunum deneyimi.",
      wing10Title: "Selam Olsun Sana Ey Peygamber ﷺ",
      wing10Desc: "Doğumdan vefata kadar Siyer olaylarının kronolojik özeti.",
      wing11Title: "Şerefli Peygamber Odası",
      wing11Desc: "Şerefli odanın boyutları ve olaylarının ayrıntılı açıklaması.",
      wing12Title: "Hz. Peygamber'i ﷺ Görüyormuşsunuz Gibi",
      wing12Desc: "Hz. Peygamber'in ﷺ hayatı, sıfatları ve kişilik özelliklerinin kapsamlı sunumu.",
      wing13Title: "Peygamberleri Görüyormuşsunuz Gibi",
      wing13Desc: "Peygamberlerin dönemleri, mucizeleri ve ahlakının özgün sunumu.",
      wing14Title: "Ek Kanat",
      wing14Desc: "Tutarlı tasarımla gelecekteki bir kanat için ayrılmıştır.",
    },
    tech: {
      badge: "Yenilikçi Teknolojiler",
      sectionTitle: "Müze Teknolojileri",
      sectionDescription: "Müze deneyiminizi eşsiz ve unutulmaz kılan en son interaktif teknolojileri keşfedin",
      immersiveRooms: "Sürükleyici Odalar",
      atlases3d: "3D Atlaslar",
      hologram: "Hologram",
      ai: "Yapay Zekâ",
      cinemaHalls: "Sinema Salonları",
      interactiveScreens: "İnteraktif Ekranlar",
      interactiveMurals: "İnteraktif Duvar Resimleri",
      models3d: "3D Modeller",
      childrenRooms: "İnteraktif Çocuk Odaları",
      interactiveArtifacts: "İnteraktif Eserler",
      vr: "Sanal Gerçeklik (VR)",
      interactiveModels: "İnteraktif Modeller",
    },
    planVisit: {
      sectionTitle: "Ziyaretinizi Planlayın",
      sectionDescription: "Zengin bir müze deneyimi için bilmeniz gereken her şey",
      feature1Title: "Güvenli ve Emniyetli",
      feature1Desc: "Kişisel bilgilerinizi koruyan şifreli ödeme sistemimiz ile güvenle rezervasyon yapın",
      feature2Title: "Önceden Rezerve Edin",
      feature2Desc: "Müsaitliği garanti altına almak ve kuyrukta beklemekten kaçınmak için tercih ettiğiniz tarih ve saati çevrimiçi olarak ayırtın",
      feature3Title: "Herkes İçin",
      feature3Desc: "İslam mirasını keşfetmek isteyen aileler, öğrenciler, araştırmacılar ve dünyanın dört bir yanından ziyaretçiler için ideal",
    },
    locations: {
      sectionTitle: "Küresel Konumlarımız",
      sectionSubtitle: "Üç kıtadaki dünya standartlarındaki müzelerimizi ziyaret edin",
      sectionQuestion: "Hangi şubeyi ziyaret etmek istersiniz?",
      openNow: "Şimdi Açık",
      ticketsFrom: "Biletler şu fiyattan başlar",
      bookVisit: "Ziyaret rezervasyonu yap",
      visitInfo: "Ziyaret Bilgileri",
      visitInfoDesc: "Ziyaretiniz için bilmeniz gereken her şey",
      whatsIncluded: "Neler Dahil",
      durationTiming: "Süre ve Zamanlama",
      duration: "Süre:",
      workingHours: "Çalışma Saatleri:",
      cancellationPolicy: "İptal Politikası",
      mecca: "Mekke",
      medina: "Medine",
      rabat: "Rabat",
      nouakchott: "Nuakşot",
      dakar: "Dakar",
      countrySA: "Suudi Arabistan",
      countryMorocco: "Fas",
      countryMauritania: "Moritanya",
      countrySenegal: "Senegal",
      addressMecca: "Kral Abdulaziz Vakfı, Saat Kulesi, 2. Kat",
      addressMedina: "Peygamber Mescidi Güney Avlusu, Ravza karşısı",
      addressRabat: "UNESCO Binası",
      addressNouakchott: "Nuakşot Şube Adresi",
      addressDakar: "Dakar Şube Adresi",
      guidedTour: "Tercih ettiğiniz dilde rehberli tur",
      allSections60: "60'tan fazla sergi bölümüne erişim",
      allSections: "Tüm sergi bölümlerine erişim",
      interactiveDisplays3d: "İnteraktif sergiler ve 3D model deneyimi",
      interactiveDisplays: "İnteraktif sergi deneyimi",
      cinemaExperience: "Sinema salonu deneyimi",
      freeGuide: "Ücretsiz müze rehber kitapçığı",
      duration23: "2-3 saat",
      hoursSatThu: "Cumartesi - Perşembe 09:00 - 21:00",
      hoursMonSat: "Pazartesi - Cumartesi 10:00 - 20:00",
      hoursMonSat2: "Pazartesi - Cumartesi 10:00 - 18:00",
      hoursSatThu2: "Cumartesi - Perşembe 09:00 - 18:00",
      closedFri: "Cuma günleri kapalı",
      closedSun: "Pazar günleri kapalı",
      cancel24: "Ziyaretten 24 saat öncesine kadar ücretsiz iptal",
      cancel48: "Ziyaretten 48 saat öncesine kadar ücretsiz iptal",
      noRefund24: "24 saat içinde iptallerde iade yapılmaz",
      noRefund48: "48 saat içinde iptallerde iade yapılmaz",
      reschedule: "Müsaitliğe göre yeniden planlama mümkündür",
    },
    testimonials: {
      sectionTitle: "Ziyaretçilerimiz Ne Diyor",
      sectionDescription: "Dünya genelinden ziyaretçi deneyimlerini keşfedin",
      pages: "sayfa",
      of: "/",
      t1text: "Kesinlikle nefes kesici bir deneyim! Sürükleyici sergiler ve tarihi modeller Hz. Peygamber'in ﷺ hayatını canlandırdı. İslam mirasını anlamak isteyen herkes için mutlaka görülmeli.",
      t1highlight: "Kesinlikle nefes kesici bir deneyim!",
      t1name: "Fatima Hassan",
      t1location: "Mekke Şubesini ziyaret etti",
      t2text: "İnteraktif teknoloji ve güzel sergiler, İslam medeniyeti hakkında öğrenmeyi tüm ailemiz için ilgi çekici hale getirdi. Çocuklar özellikle 3D şehir modellerine hayran kaldı.",
      t2highlight: "İnteraktif teknoloji ve güzel sergiler",
      t2name: "Ahmed Al-Rashed",
      t2location: "Medine Şubesini ziyaret etti",
      t3text: "Modern teknolojiyi tarih saygısıyla birleştiren dünya standartlarında bir müze. Çok dilli turlar mükemmeldi ve personel bilgili ve çok misafirperverdi.",
      t3highlight: "Dünya standartlarında bir müze",
      t3name: "Mohammed Benzema",
      t3location: "Rabat Şubesini ziyaret etti",
      t4text: "Unutulmaz bir ruhani ziyaret! Hz. Peygamber'in ﷺ Sîresine daha önce hayal edemeyeceğim bir şekilde yakınlık hissettim. Mekân huzur ve imanla dolu.",
      t4highlight: "Unutulmaz bir ruhani ziyaret!",
      t4name: "Aisha Al-Mansoori",
      t4location: "Dubai Şubesini ziyaret etti",
      t5text: "Şimdiye kadar yaşadığım en iyi kültürel deneyim. Her kanattaki titiz detaylar bu müzenin ne kadar özenle yapıldığını gösteriyor.",
      t5highlight: "Şimdiye kadar yaşadığım en iyi kültürel deneyim.",
      t5name: "Khalid Al-Otaibi",
      t5location: "Cidde Şubesini ziyaret etti",
      t6text: "Ailemi bir tura çıkardım ve çok mutlu oldular. Tasarım her yaşa hitap ediyor ve bilgiyi akıcı ve etkili bir şekilde sunuyor.",
      t6highlight: "Tasarım her yaşa hitap ediyor",
      t6name: "Sara Al-Qahtani",
      t6location: "Riyad Şubesini ziyaret etti",
      t7text: "Çocuklar ve yetişkinler için harika bir eğitim deneyimi. Her aileye bu müzeyi ziyaret etmesini tavsiye ederim.",
      t7highlight: "Harika bir eğitim deneyimi",
      t7name: "Youssef Al-Harbi",
      t7location: "Dammam Şubesini ziyaret etti",
      t8text: "Müze, Hz. Peygamber'in Sîresini muhteşem bir şekilde somutlaştırıyor. Zengin İslam tarihimizle gurur duyarak ayrıldım.",
      t8highlight: "Müze, Hz. Peygamber'in Sîresini muhteşem bir şekilde somutlaştırıyor.",
      t8name: "Noura Al-Subaie",
      t8location: "Kuveyt Şubesini ziyaret etti",
    },
    footer: {
      description: "İslam mirasını kutlayan ve Hz. Peygamber'in ﷺ hikâyesini en son teknolojiler ve interaktif sergilerle anlatan küresel bir müze.",
      quickLinks: "Hızlı Bağlantılar",
      home: "Ana Sayfa",
      aboutMuseum: "Müze Hakkında",
      exhibitions: "Sergiler",
      events: "Etkinlikler",
      contactUs: "Bize Ulaşın",
      branches: "Şubelerimiz",
      branchMecca: "Mekke Şubesi",
      branchMedina: "Medine Şubesi",
      branchRabat: "Rabat Şubesi",
      branchNouakchott: "Nuakşot Şubesi",
      branchDakar: "Dakar Şubesi",
      contactTitle: "Bize Ulaşın",
      address: "Mekke, Suudi Arabistan",
      copyright: "© 2024 Siyer Müzesi. Tüm hakları saklıdır.",
      privacy: "Gizlilik Politikası",
      terms: "Şartlar ve Koşullar",
    },
  },
  ru: {
    nav: {
      home: "Главная",
      wings: "Крылья музея",
      locations: "Локации",
      technologies: "Технологии",
      planVisit: "Спланируйте визит",
      bookTicket: "Купить билет",
    },
    hero: {
      badge: "Погрузитесь в Сиру",
      titleLine1: "Международный",
      titleLine2: "Музей Сиры Пророка",
      description: "Откройте для себя глубокое наследие Пророка Мухаммада ﷺ через подлинные технологии и захватывающие истории в",
      descriptionLine2: "пяти престижных локациях по всему миру",
      bookVisit: "Забронировать визит",
      availableIn: "Доступно на:",
      langRussian: "Русский",
      langTurkish: "Турецкий",
      langIndonesian: "Индонезийский",
      langUrdu: "Урду",
      langFrench: "Французский",
      langEnglish: "Английский",
      langArabic: "Арабский",
    },
    wings: {
      sectionTitle: "Крылья музея",
      sectionDescription: "Духовное и историческое путешествие через 14 крыльев, каждое из которых рассказывает уникальную историю веры и исламской истории",
      statWings: "Уникальных крыльев",
      statMaterials: "Научных материалов",
      statExperience: "Духовный опыт",
      moreWings: "Больше крыльев",
      showing: "Показано",
      of: "из",
      wing: "крыльев",
      exploreWing: "Исследовать крыло",
      prev: "Назад",
      next: "Далее",
      goTo: "Перейти к",
      wing1Title: "Хвала Аллаху, Всемогущему",
      wing1Desc: "Всеобъемлющее введение об Аллахе, Его именах, атрибутах и знамениях Его могущества из 100 000 материалов.",
      wing2Title: "Имущество и вещи Пророка ﷺ",
      wing2Desc: "Уникальный опыт, демонстрирующий всё, что использовал Пророк ﷺ, с описаниями из Сунны.",
      wing3Title: "Путь Хиджры",
      wing3Desc: "Демонстрация пути переселения Пророка ﷺ в Медину и ключевых событий.",
      wing4Title: "Пророк ﷺ и женщины",
      wing4Desc: "Всеобъемлющая экспозиция, подчеркивающая статус женщин в эпоху Пророка ﷺ с более чем 350 почестями.",
      wing5Title: "Пророк ﷺ и дети",
      wing5Desc: "Экспозиция, демонстрирующая более 250 похвальных взаимодействий детей с Пророком ﷺ.",
      wing6Title: "Шатёр пророческой медицины",
      wing6Desc: "Научная выставка о болезнях, лечении и полезных продуктах, упомянутых в Коране и Сунне.",
      wing7Title: "Достоинства и качества Пророка ﷺ",
      wing7Desc: "Подробности об именах, атрибутах, одежде, пище и внешности Пророка ﷺ.",
      wing8Title: "Как будто вы рядом с Пророком ﷺ",
      wing8Desc: "Творческая презентация жизни Пророка ﷺ в Мекке и Медине с использованием уникальных технологий.",
      wing9Title: "Как будто вы рядом с Пророком ﷺ (альтернатива)",
      wing9Desc: "Та же концепция с другим визуальным представлением.",
      wing10Title: "Мир тебе, о Пророк ﷺ",
      wing10Desc: "Хронологическое изложение событий Сиры от рождения до кончины.",
      wing11Title: "Благородная комната Пророка",
      wing11Desc: "Точное описание благородной комнаты, её размеров и связанных событий.",
      wing12Title: "Пророк ﷺ — как если бы вы его видели",
      wing12Desc: "Всеобъемлющая экспозиция жизни, атрибутов и личностных качеств Пророка ﷺ.",
      wing13Title: "Пророки — как если бы вы их видели",
      wing13Desc: "Уникальная экспозиция о пророках, их эпохах, чудесах и нравах.",
      wing14Title: "Дополнительное крыло",
      wing14Desc: "Зарезервировано для будущего крыла с единым дизайном.",
    },
    tech: {
      badge: "Инновационные технологии",
      sectionTitle: "Технологии музея",
      sectionDescription: "Откройте для себя новейшие интерактивные технологии, которые делают ваш музейный опыт уникальным и незабываемым",
      immersiveRooms: "Иммерсивные комнаты",
      atlases3d: "3D-атласы",
      hologram: "Голограмма",
      ai: "Искусственный интеллект",
      cinemaHalls: "Кинозалы",
      interactiveScreens: "Интерактивные экраны",
      interactiveMurals: "Интерактивные фрески",
      models3d: "3D-модели",
      childrenRooms: "Интерактивные детские комнаты",
      interactiveArtifacts: "Интерактивные артефакты",
      vr: "Виртуальная реальность (VR)",
      interactiveModels: "Интерактивные модели",
    },
    planVisit: {
      sectionTitle: "Спланируйте визит",
      sectionDescription: "Всё, что нужно знать для богатого музейного опыта",
      feature1Title: "Безопасно и надёжно",
      feature1Desc: "Бронируйте с уверенностью через нашу зашифрованную платёжную систему, которая защищает вашу личную информацию",
      feature2Title: "Бронируйте заранее",
      feature2Desc: "Забронируйте удобную дату и время онлайн, чтобы гарантировать наличие мест и избежать очередей",
      feature3Title: "Для всех",
      feature3Desc: "Идеально для семей, студентов, исследователей и посетителей со всего мира, желающих изучить исламское наследие",
    },
    locations: {
      sectionTitle: "Наши мировые локации",
      sectionSubtitle: "Посетите наши музеи мирового класса на трёх континентах",
      sectionQuestion: "Какой филиал вы хотите посетить?",
      openNow: "Открыто сейчас",
      ticketsFrom: "Билеты от",
      bookVisit: "Забронировать визит в",
      visitInfo: "Информация о визите",
      visitInfoDesc: "Всё, что нужно знать для вашего визита",
      whatsIncluded: "Что включено",
      durationTiming: "Продолжительность и время",
      duration: "Продолжительность:",
      workingHours: "Часы работы:",
      cancellationPolicy: "Политика отмены",
      mecca: "Мекка",
      medina: "Медина",
      rabat: "Рабат",
      nouakchott: "Нуакшот",
      dakar: "Дакар",
      countrySA: "Саудовская Аравия",
      countryMorocco: "Марокко",
      countryMauritania: "Мавритания",
      countrySenegal: "Сенегал",
      addressMecca: "Вакф короля Абдулазиза, Часовая башня, 2 этаж",
      addressMedina: "Южный двор Мечети Пророка, напротив Ар-Равда",
      addressRabat: "Здание ЮНЕСКО",
      addressNouakchott: "Адрес филиала в Нуакшоте",
      addressDakar: "Адрес филиала в Дакаре",
      guidedTour: "Экскурсия на выбранном вами языке",
      allSections60: "Доступ ко всем 60+ разделам выставки",
      allSections: "Доступ ко всем разделам выставки",
      interactiveDisplays3d: "Интерактивные экспозиции и 3D-модели",
      interactiveDisplays: "Интерактивные экспозиции",
      cinemaExperience: "Опыт кинозала",
      freeGuide: "Бесплатный путеводитель по музею",
      duration23: "2-3 часа",
      hoursSatThu: "Суббота - Четверг 9:00 - 21:00",
      hoursMonSat: "Понедельник - Суббота 10:00 - 20:00",
      hoursMonSat2: "Понедельник - Суббота 10:00 - 18:00",
      hoursSatThu2: "Суббота - Четверг 9:00 - 18:00",
      closedFri: "Закрыто по пятницам",
      closedSun: "Закрыто по воскресеньям",
      cancel24: "Бесплатная отмена за 24 часа до визита",
      cancel48: "Бесплатная отмена за 48 часов до визита",
      noRefund24: "Без возврата при отмене менее чем за 24 часа",
      noRefund48: "Без возврата при отмене менее чем за 48 часов",
      reschedule: "Перенос возможен при наличии мест",
    },
    testimonials: {
      sectionTitle: "Что говорят наши посетители",
      sectionDescription: "Откройте для себя впечатления посетителей со всего мира",
      pages: "стр.",
      of: "из",
      t1text: "Абсолютно захватывающий опыт! Иммерсивные экспозиции и исторические модели оживили жизнь Пророка ﷺ. Обязательно к посещению для всех, кто хочет понять исламское наследие.",
      t1highlight: "Абсолютно захватывающий опыт!",
      t1name: "Фатима Хассан",
      t1location: "Посетила филиал в Мекке",
      t2text: "Интерактивные технологии и красивые экспонаты сделали изучение исламской цивилизации увлекательным для всей нашей семьи.",
      t2highlight: "Интерактивные технологии и красивые экспонаты",
      t2name: "Ахмед Ар-Рашед",
      t2location: "Посетил филиал в Медине",
      t3text: "Музей мирового класса, сочетающий современные технологии с глубоким уважением к истории. Многоязычные экскурсии были превосходными.",
      t3highlight: "Музей мирового класса",
      t3name: "Мохаммед Бензема",
      t3location: "Посетил филиал в Рабате",
      t4text: "Незабываемый духовный визит! Я почувствовал близость к Сире Пророка ﷺ так, как никогда не мог себе представить.",
      t4highlight: "Незабываемый духовный визит!",
      t4name: "Аиша Аль-Мансури",
      t4location: "Посетила филиал в Дубае",
      t5text: "Лучший культурный опыт в моей жизни. Тщательное внимание к деталям в каждом крыле показывает заботу, с которой построен этот музей.",
      t5highlight: "Лучший культурный опыт в моей жизни.",
      t5name: "Халид Аль-Отайби",
      t5location: "Посетил филиал в Джидде",
      t6text: "Я взял родителей на экскурсию, и они были очень счастливы. Дизайн подходит для всех возрастов.",
      t6highlight: "Дизайн подходит для всех возрастов",
      t6name: "Сара Аль-Кахтани",
      t6location: "Посетила филиал в Эр-Рияде",
      t7text: "Замечательный образовательный опыт для детей и взрослых. Рекомендую каждой семье посетить этот музей.",
      t7highlight: "Замечательный образовательный опыт",
      t7name: "Юсуф Аль-Харби",
      t7location: "Посетил филиал в Даммаме",
      t8text: "Музей великолепно воплощает Сиру Пророка. Я ушёл, гордясь нашей богатой исламской историей.",
      t8highlight: "Музей великолепно воплощает Сиру Пророка.",
      t8name: "Нура Ас-Субайе",
      t8location: "Посетила филиал в Кувейте",
    },
    footer: {
      description: "Всемирный музей, посвящённый исламскому наследию и рассказывающий историю Пророка ﷺ с помощью новейших технологий и интерактивных экспозиций.",
      quickLinks: "Быстрые ссылки",
      home: "Главная",
      aboutMuseum: "О музее",
      exhibitions: "Выставки",
      events: "События",
      contactUs: "Связаться с нами",
      branches: "Наши филиалы",
      branchMecca: "Филиал в Мекке",
      branchMedina: "Филиал в Медине",
      branchRabat: "Филиал в Рабате",
      branchNouakchott: "Филиал в Нуакшоте",
      branchDakar: "Филиал в Дакаре",
      contactTitle: "Связаться с нами",
      address: "Мекка, Саудовская Аравия",
      copyright: "© 2024 Музей Сиры. Все права защищены.",
      privacy: "Политика конфиденциальности",
      terms: "Условия использования",
    },
  },
  ur: {
    nav: {
      home: "ہوم",
      wings: "میوزیم ونگز",
      locations: "مقامات",
      technologies: "ٹیکنالوجیز",
      planVisit: "اپنے دورے کی منصوبہ بندی کریں",
      bookTicket: "ٹکٹ بک کریں",
    },
    hero: {
      badge: "سیرت کا تجربہ کریں",
      titleLine1: "بین الاقوامی",
      titleLine2: "سیرت میوزیم",
      description: "نبی کریم محمد ﷺ کی گہری وراثت کو مستند ٹیکنالوجی اور دلکش کہانیوں کے ذریعے دریافت کریں",
      descriptionLine2: "دنیا بھر میں پانچ معتبر مقامات پر",
      bookVisit: "اپنا دورہ بک کریں",
      availableIn: "دستیاب زبانیں:",
      langRussian: "روسی",
      langTurkish: "ترکی",
      langIndonesian: "انڈونیشین",
      langUrdu: "اردو",
      langFrench: "فرانسیسی",
      langEnglish: "انگریزی",
      langArabic: "عربی",
    },
    wings: {
      sectionTitle: "میوزیم ونگز",
      sectionDescription: "14 ونگز کے ذریعے ایک روحانی اور تاریخی سفر، ہر ایک ایمان اور اسلامی تاریخ کی ایک منفرد کہانی سناتا ہے",
      statWings: "منفرد ونگز",
      statMaterials: "سائنسی مواد",
      statExperience: "روحانی تجربہ",
      moreWings: "مزید ونگز",
      showing: "دکھایا جا رہا ہے",
      of: "میں سے",
      wing: "ونگز",
      exploreWing: "ونگ دریافت کریں",
      prev: "پچھلا",
      next: "اگلا",
      goTo: "جائیں",
      wing1Title: "اللہ عزوجل کی حمد",
      wing1Desc: "اللہ، اس کے ناموں، صفات اور اس کی قدرت کے دلائل کا جامع تعارف، 100,000 مواد سے اخذ کیا گیا۔",
      wing2Title: "نبی ﷺ کا سامان اور اثاثے",
      wing2Desc: "نبی ﷺ نے جو کچھ استعمال کیا اس کی نمائش، بشمول فرنیچر، برتن اور ذاتی سامان، سنت سے وضاحت کے ساتھ۔",
      wing3Title: "ہجرت کا راستہ",
      wing3Desc: "نبی ﷺ کی مدینہ منورہ کی طرف ہجرت کے راستے اور اہم واقعات کی نمائش۔",
      wing4Title: "نبی ﷺ اور خواتین",
      wing4Desc: "نبی ﷺ کے دور میں خواتین کے مقام کو 350 سے زیادہ اعزازات کے ساتھ اجاگر کرنے والی جامع نمائش۔",
      wing5Title: "نبی ﷺ اور بچے",
      wing5Desc: "بچوں کی نبی ﷺ کے ساتھ 250 سے زیادہ قابل تحسین بات چیت کی نمائش۔",
      wing6Title: "طب نبوی کا خیمہ",
      wing6Desc: "قرآن اور سنت میں مذکور بیماریوں، علاج اور مفید غذاؤں کی سائنسی نمائش۔",
      wing7Title: "نبی ﷺ کے فضائل اور خصائل",
      wing7Desc: "نبی ﷺ کے ناموں، صفات، لباس، خوراک اور ظاہری شکل کے بارے میں تفصیلات۔",
      wing8Title: "گویا آپ نبی ﷺ کے ساتھ ہیں",
      wing8Desc: "منفرد ٹیکنالوجیز کا استعمال کرتے ہوئے مکہ اور مدینہ میں نبی ﷺ کی زندگی کی تخلیقی پیشکش۔",
      wing9Title: "گویا آپ نبی ﷺ کے ساتھ ہیں (متبادل)",
      wing9Desc: "وہی تصور مختلف بصری پیشکش کے تجربے کے ساتھ۔",
      wing10Title: "السلام علیک اے نبی ﷺ",
      wing10Desc: "ولادت سے وفات تک سیرت کے واقعات کا تاریخی خلاصہ۔",
      wing11Title: "حجرہ نبوی شریف",
      wing11Desc: "حجرہ شریف، اس کے ابعاد اور واقعات کی تفصیلی وضاحت۔",
      wing12Title: "نبی ﷺ گویا آپ انہیں دیکھ رہے ہیں",
      wing12Desc: "نبی ﷺ کی زندگی، صفات اور شخصیت کے خدوخال کی جامع نمائش۔",
      wing13Title: "انبیاء گویا آپ انہیں دیکھ رہے ہیں",
      wing13Desc: "انبیاء، ان کے ادوار، معجزات اور آداب کی منفرد نمائش۔",
      wing14Title: "اضافی ونگ",
      wing14Desc: "مستقبل کے ونگ کے لیے مربوط ڈیزائن کے ساتھ مخصوص۔",
    },
    tech: {
      badge: "جدید ٹیکنالوجیز",
      sectionTitle: "میوزیم ٹیکنالوجیز",
      sectionDescription: "جدید ترین انٹرایکٹو ٹیکنالوجیز دریافت کریں جو آپ کے میوزیم کے تجربے کو منفرد اور یادگار بناتی ہیں",
      immersiveRooms: "امرسیو کمرے",
      atlases3d: "3D اٹلس",
      hologram: "ہولوگرام",
      ai: "مصنوعی ذہانت",
      cinemaHalls: "سنیما ہال",
      interactiveScreens: "انٹرایکٹو اسکرینز",
      interactiveMurals: "انٹرایکٹو دیواری تصاویر",
      models3d: "3D ماڈلز",
      childrenRooms: "بچوں کے انٹرایکٹو کمرے",
      interactiveArtifacts: "انٹرایکٹو نوادرات",
      vr: "ورچوئل ریئلٹی (VR)",
      interactiveModels: "انٹرایکٹو ماڈلز",
    },
    planVisit: {
      sectionTitle: "اپنے دورے کی منصوبہ بندی کریں",
      sectionDescription: "ایک بھرپور میوزیم تجربے کے لیے آپ کو جو کچھ جاننے کی ضرورت ہے",
      feature1Title: "محفوظ اور مامون",
      feature1Desc: "ہمارے انکرپٹڈ ادائیگی کے نظام کے ذریعے اعتماد کے ساتھ بکنگ کریں جو آپ کی ذاتی معلومات کی حفاظت کرتا ہے",
      feature2Title: "پیشگی بک کریں",
      feature2Desc: "دستیابی یقینی بنانے اور قطاروں سے بچنے کے لیے اپنی پسندیدہ تاریخ اور وقت آن لائن محفوظ کریں",
      feature3Title: "سب کے لیے",
      feature3Desc: "خاندانوں، طلباء، محققین اور دنیا بھر سے آنے والے زائرین کے لیے مثالی جو اسلامی ورثے کو دریافت کرنا چاہتے ہیں",
    },
    locations: {
      sectionTitle: "ہمارے عالمی مقامات",
      sectionSubtitle: "تین براعظموں میں ہمارے عالمی معیار کے میوزیمز کا دورہ کریں",
      sectionQuestion: "آپ کون سی شاخ کا دورہ کرنا چاہیں گے؟",
      openNow: "ابھی کھلا ہے",
      ticketsFrom: "ٹکٹ شروع ہوتے ہیں",
      bookVisit: "دورے کی بکنگ",
      visitInfo: "دورے کی معلومات",
      visitInfoDesc: "آپ کے دورے کے لیے ضروری معلومات",
      whatsIncluded: "کیا شامل ہے",
      durationTiming: "دورانیہ اور وقت",
      duration: "دورانیہ:",
      workingHours: "کام کے اوقات:",
      cancellationPolicy: "منسوخی کی پالیسی",
      mecca: "مکہ مکرمہ",
      medina: "مدینہ منورہ",
      rabat: "رباط",
      nouakchott: "نواکشوط",
      dakar: "ڈکار",
      countrySA: "سعودی عرب",
      countryMorocco: "مراکش",
      countryMauritania: "موریطانیہ",
      countrySenegal: "سینیگال",
      addressMecca: "کنگ عبدالعزیز وقف، کلاک ٹاور، دوسری منزل",
      addressMedina: "مسجد نبوی کا جنوبی صحن، روضہ کے سامنے",
      addressRabat: "یونیسکو بلڈنگ",
      addressNouakchott: "نواکشوط برانچ کا پتہ",
      addressDakar: "ڈکار برانچ کا پتہ",
      guidedTour: "آپ کی پسندیدہ زبان میں گائیڈڈ ٹور",
      allSections60: "60 سے زیادہ نمائشی حصوں تک رسائی",
      allSections: "تمام نمائشی حصوں تک رسائی",
      interactiveDisplays3d: "انٹرایکٹو ڈسپلے اور 3D ماڈلز کا تجربہ",
      interactiveDisplays: "انٹرایکٹو ڈسپلے کا تجربہ",
      cinemaExperience: "سنیما ہال کا تجربہ",
      freeGuide: "مفت میوزیم گائیڈ بک",
      duration23: "2-3 گھنٹے",
      hoursSatThu: "ہفتہ - جمعرات صبح 9:00 - شام 9:00",
      hoursMonSat: "پیر - ہفتہ صبح 10:00 - شام 8:00",
      hoursMonSat2: "پیر - ہفتہ صبح 10:00 - شام 6:00",
      hoursSatThu2: "ہفتہ - جمعرات صبح 9:00 - شام 6:00",
      closedFri: "جمعہ کو بند",
      closedSun: "اتوار کو بند",
      cancel24: "دورے سے 24 گھنٹے پہلے تک مفت منسوخی",
      cancel48: "دورے سے 48 گھنٹے پہلے تک مفت منسوخی",
      noRefund24: "24 گھنٹوں کے اندر منسوخی پر کوئی واپسی نہیں",
      noRefund48: "48 گھنٹوں کے اندر منسوخی پر کوئی واپسی نہیں",
      reschedule: "دستیابی کی بنیاد پر دوبارہ شیڈول ممکن ہے",
    },
    testimonials: {
      sectionTitle: "ہمارے زائرین کیا کہتے ہیں",
      sectionDescription: "دنیا بھر سے زائرین کے تجربات دریافت کریں",
      pages: "صفحات",
      of: "میں سے",
      t1text: "واقعی دل موہ لینے والا تجربہ! امرسیو ڈسپلے اور تاریخی ماڈلز نے نبی ﷺ کی زندگی کو جیتا جاگتا بنا دیا۔ اسلامی ورثے کو سمجھنے کے خواہشمند ہر شخص کے لیے ضرور دیکھنے والی جگہ۔",
      t1highlight: "واقعی دل موہ لینے والا تجربہ!",
      t1name: "فاطمہ حسن",
      t1location: "مکہ برانچ کا دورہ کیا",
      t2text: "انٹرایکٹو ٹیکنالوجی اور خوبصورت نمائشوں نے اسلامی تہذیب کے بارے میں سیکھنا ہمارے پورے خاندان کے لیے دلچسپ بنا دیا۔",
      t2highlight: "انٹرایکٹو ٹیکنالوجی اور خوبصورت نمائشیں",
      t2name: "احمد الراشد",
      t2location: "مدینہ برانچ کا دورہ کیا",
      t3text: "عالمی معیار کا میوزیم جو جدید ٹیکنالوجی کو تاریخ کے گہرے احترام کے ساتھ جوڑتا ہے۔ کثیر لسانی ٹور بہترین تھے۔",
      t3highlight: "عالمی معیار کا میوزیم",
      t3name: "محمد بنزیمہ",
      t3location: "رباط برانچ کا دورہ کیا",
      t4text: "ایک ناقابل فراموش روحانی دورہ! میں نے نبی ﷺ کی سیرت سے ایسی قربت محسوس کی جس کا میں نے کبھی تصور نہیں کیا تھا۔",
      t4highlight: "ایک ناقابل فراموش روحانی دورہ!",
      t4name: "عائشہ المنصوری",
      t4location: "دبئی برانچ کا دورہ کیا",
      t5text: "میری زندگی کا بہترین ثقافتی تجربہ۔ ہر ونگ میں باریک تفصیلات اس محبت کو ظاہر کرتی ہیں جس سے یہ میوزیم بنایا گیا۔",
      t5highlight: "میری زندگی کا بہترین ثقافتی تجربہ۔",
      t5name: "خالد العتیبی",
      t5location: "جدہ برانچ کا دورہ کیا",
      t6text: "میں اپنے والدین کو ٹور پر لے گیا اور وہ بہت خوش ہوئے۔ ڈیزائن ہر عمر کے لیے موزوں ہے۔",
      t6highlight: "ڈیزائن ہر عمر کے لیے موزوں ہے",
      t6name: "سارہ القحطانی",
      t6location: "ریاض برانچ کا دورہ کیا",
      t7text: "بچوں اور بڑوں کے لیے ایک شاندار تعلیمی تجربہ۔ میں ہر خاندان کو اس میوزیم کا دورہ کرنے کی سفارش کرتا ہوں۔",
      t7highlight: "ایک شاندار تعلیمی تجربہ",
      t7name: "یوسف الحربی",
      t7location: "دمام برانچ کا دورہ کیا",
      t8text: "میوزیم نبی ﷺ کی سیرت کو شاندار طریقے سے پیش کرتا ہے۔ میں اپنی شاندار اسلامی تاریخ پر فخر محسوس کرتے ہوئے واپس آیا۔",
      t8highlight: "میوزیم نبی ﷺ کی سیرت کو شاندار طریقے سے پیش کرتا ہے۔",
      t8name: "نورہ السبیعی",
      t8location: "کویت برانچ کا دورہ کیا",
    },
    footer: {
      description: "ایک عالمی میوزیم جو اسلامی ورثے کو خراج عقیدت پیش کرتا ہے اور جدید ترین ٹیکنالوجیز اور انٹرایکٹو نمائشوں کے ذریعے نبی ﷺ کی کہانی بیان کرتا ہے۔",
      quickLinks: "فوری لنکس",
      home: "ہوم",
      aboutMuseum: "میوزیم کے بارے میں",
      exhibitions: "نمائشیں",
      events: "تقریبات",
      contactUs: "ہم سے رابطہ کریں",
      branches: "ہماری شاخیں",
      branchMecca: "مکہ برانچ",
      branchMedina: "مدینہ برانچ",
      branchRabat: "رباط برانچ",
      branchNouakchott: "نواکشوط برانچ",
      branchDakar: "ڈکار برانچ",
      contactTitle: "ہم سے رابطہ کریں",
      address: "مکہ مکرمہ، سعودی عرب",
      copyright: "© 2024 سیرت میوزیم۔ جملہ حقوق محفوظ ہیں۔",
      privacy: "رازداری کی پالیسی",
      terms: "شرائط و ضوابط",
    },
  },
  id: {
    nav: {
      home: "Beranda",
      wings: "Sayap Museum",
      locations: "Lokasi",
      technologies: "Teknologi",
      planVisit: "Rencanakan Kunjungan",
      bookTicket: "Pesan Tiket",
    },
    hero: {
      badge: "Rasakan Sirah",
      titleLine1: "Museum Internasional",
      titleLine2: "Sirah Nabi",
      description: "Rasakan warisan mendalam Nabi Muhammad ﷺ melalui teknologi autentik dan penceritaan imersif di",
      descriptionLine2: "lima lokasi bergengsi di seluruh dunia",
      bookVisit: "Pesan Kunjungan Anda",
      availableIn: "Tersedia dalam:",
      langRussian: "Rusia",
      langTurkish: "Turki",
      langIndonesian: "Indonesia",
      langUrdu: "Urdu",
      langFrench: "Prancis",
      langEnglish: "Inggris",
      langArabic: "Arab",
    },
    wings: {
      sectionTitle: "Sayap Museum",
      sectionDescription: "Perjalanan spiritual dan historis melalui 14 sayap, masing-masing menceritakan kisah unik tentang iman dan sejarah Islam",
      statWings: "Sayap Berbeda",
      statMaterials: "Materi Ilmiah",
      statExperience: "Pengalaman Spiritual",
      moreWings: "Lebih Banyak Sayap",
      showing: "Menampilkan",
      of: "dari",
      wing: "sayap",
      exploreWing: "Jelajahi Sayap",
      prev: "Sebelumnya",
      next: "Selanjutnya",
      goTo: "Pergi ke",
      wing1Title: "Pujian kepada Allah, Yang Maha Kuasa",
      wing1Desc: "Pengenalan komprehensif tentang Allah, nama-nama-Nya, sifat-sifat-Nya, dan tanda-tanda kekuasaan-Nya dari 100.000 materi dan topik.",
      wing2Title: "Perabotan & Barang Milik Nabi ﷺ",
      wing2Desc: "Pengalaman unik yang menampilkan segala yang digunakan Nabi ﷺ termasuk perabotan, wadah, dan barang-barang pribadi dengan deskripsi dari Sunnah.",
      wing3Title: "Rute Hijrah",
      wing3Desc: "Tampilan jalur hijrah Nabi ﷺ ke Madinah dan peristiwa-peristiwa penting di sepanjang perjalanan.",
      wing4Title: "Nabi ﷺ dan Perempuan",
      wing4Desc: "Tampilan komprehensif yang menyoroti status perempuan di era Nabi ﷺ dengan daftar kehormatan lebih dari 350 penghargaan.",
      wing5Title: "Nabi ﷺ dan Anak-anak",
      wing5Desc: "Tampilan yang menampilkan lebih dari 250 interaksi terpuji anak-anak dengan Nabi ﷺ.",
      wing6Title: "Tenda Pengobatan Nabawi",
      wing6Desc: "Pameran ilmiah tentang penyakit, pengobatan, dan makanan bermanfaat yang disebutkan dalam Al-Quran dan Sunnah.",
      wing7Title: "Keutamaan & Sifat Nabi ﷺ",
      wing7Desc: "Detail tentang nama, sifat, pakaian, makanan, dan penampilan Nabi ﷺ.",
      wing8Title: "Seolah Anda Bersama Nabi ﷺ",
      wing8Desc: "Tampilan kreatif kehidupan Nabi ﷺ di Mekah dan Madinah menggunakan teknologi unik.",
      wing9Title: "Seolah Anda Bersama Nabi ﷺ (Alternatif)",
      wing9Desc: "Konsep yang sama dengan pengalaman presentasi visual yang berbeda.",
      wing10Title: "Salam Sejahtera Untukmu, Wahai Nabi ﷺ",
      wing10Desc: "Ringkasan kronologis peristiwa Sirah dari kelahiran hingga wafat.",
      wing11Title: "Kamar Mulia Nabi",
      wing11Desc: "Deskripsi detail kamar mulia, dimensi, dan peristiwa-peristiwanya.",
      wing12Title: "Nabi ﷺ Seolah Anda Melihatnya",
      wing12Desc: "Tampilan komprehensif tentang kehidupan, sifat, dan kepribadian Nabi ﷺ.",
      wing13Title: "Para Nabi Seolah Anda Melihat Mereka",
      wing13Desc: "Tampilan unik tentang para nabi, era mereka, mukjizat, dan akhlak mereka.",
      wing14Title: "Sayap Tambahan",
      wing14Desc: "Disiapkan untuk sayap masa depan dengan desain yang konsisten.",
    },
    tech: {
      badge: "Teknologi Inovatif",
      sectionTitle: "Teknologi Museum",
      sectionDescription: "Temukan teknologi interaktif terbaru yang membuat pengalaman museum Anda unik dan berkesan",
      immersiveRooms: "Ruang Imersif",
      atlases3d: "Atlas 3D",
      hologram: "Hologram",
      ai: "Kecerdasan Buatan",
      cinemaHalls: "Ruang Bioskop",
      interactiveScreens: "Layar Interaktif",
      interactiveMurals: "Mural Interaktif",
      models3d: "Model 3D",
      childrenRooms: "Ruang Interaktif Anak",
      interactiveArtifacts: "Artefak Interaktif",
      vr: "Realitas Virtual (VR)",
      interactiveModels: "Model Interaktif",
    },
    planVisit: {
      sectionTitle: "Rencanakan Kunjungan Anda",
      sectionDescription: "Semua yang perlu Anda ketahui untuk pengalaman museum yang kaya",
      feature1Title: "Aman & Terjamin",
      feature1Desc: "Pesan dengan percaya diri melalui sistem pembayaran terenkripsi kami yang melindungi informasi pribadi Anda",
      feature2Title: "Pesan di Muka",
      feature2Desc: "Reservasi tanggal dan waktu pilihan Anda secara online untuk memastikan ketersediaan dan menghindari antrean",
      feature3Title: "Untuk Semua",
      feature3Desc: "Sempurna untuk keluarga, pelajar, peneliti, dan pengunjung dari seluruh dunia yang ingin menjelajahi warisan Islam",
    },
    locations: {
      sectionTitle: "Lokasi Global Kami",
      sectionSubtitle: "Kunjungi museum kelas dunia kami di tiga benua",
      sectionQuestion: "Cabang mana yang ingin Anda kunjungi?",
      openNow: "Buka Sekarang",
      ticketsFrom: "Tiket mulai dari",
      bookVisit: "Pesan kunjungan ke",
      visitInfo: "Informasi Kunjungan",
      visitInfoDesc: "Semua yang perlu Anda ketahui untuk kunjungan Anda",
      whatsIncluded: "Yang Termasuk",
      durationTiming: "Durasi & Waktu",
      duration: "Durasi:",
      workingHours: "Jam Kerja:",
      cancellationPolicy: "Kebijakan Pembatalan",
      mecca: "Mekah",
      medina: "Madinah",
      rabat: "Rabat",
      nouakchott: "Nouakchott",
      dakar: "Dakar",
      countrySA: "Arab Saudi",
      countryMorocco: "Maroko",
      countryMauritania: "Mauritania",
      countrySenegal: "Senegal",
      addressMecca: "Wakaf Raja Abdulaziz, Menara Jam, Lantai 2",
      addressMedina: "Halaman Selatan Masjid Nabawi, di depan Raudhah",
      addressRabat: "Gedung UNESCO",
      addressNouakchott: "Alamat Cabang Nouakchott",
      addressDakar: "Alamat Cabang Dakar",
      guidedTour: "Tur berpandu dalam bahasa pilihan Anda",
      allSections60: "Akses ke 60+ bagian pameran",
      allSections: "Akses ke semua bagian pameran",
      interactiveDisplays3d: "Pengalaman tampilan interaktif dan model 3D",
      interactiveDisplays: "Pengalaman tampilan interaktif",
      cinemaExperience: "Pengalaman ruang bioskop",
      freeGuide: "Buku panduan museum gratis",
      duration23: "2-3 jam",
      hoursSatThu: "Sabtu - Kamis 09:00 - 21:00",
      hoursMonSat: "Senin - Sabtu 10:00 - 20:00",
      hoursMonSat2: "Senin - Sabtu 10:00 - 18:00",
      hoursSatThu2: "Sabtu - Kamis 09:00 - 18:00",
      closedFri: "Tutup hari Jumat",
      closedSun: "Tutup hari Minggu",
      cancel24: "Pembatalan gratis hingga 24 jam sebelum kunjungan",
      cancel48: "Pembatalan gratis hingga 48 jam sebelum kunjungan",
      noRefund24: "Tidak ada pengembalian untuk pembatalan dalam 24 jam",
      noRefund48: "Tidak ada pengembalian untuk pembatalan dalam 48 jam",
      reschedule: "Penjadwalan ulang tersedia berdasarkan ketersediaan",
    },
    testimonials: {
      sectionTitle: "Apa Kata Pengunjung Kami",
      sectionDescription: "Temukan pengalaman dari pengunjung di seluruh dunia",
      pages: "halaman",
      of: "dari",
      t1text: "Pengalaman yang benar-benar menakjubkan! Tampilan imersif dan model historis menghidupkan kehidupan Nabi ﷺ. Wajib dikunjungi bagi siapa pun yang ingin memahami warisan Islam.",
      t1highlight: "Pengalaman yang benar-benar menakjubkan!",
      t1name: "Fatima Hassan",
      t1location: "Mengunjungi Cabang Mekah",
      t2text: "Teknologi interaktif dan pameran indah membuat belajar tentang peradaban Islam menarik bagi seluruh keluarga kami. Anak-anak sangat terpesona dengan model kota 3D.",
      t2highlight: "Teknologi interaktif dan pameran indah",
      t2name: "Ahmed Al-Rashed",
      t2location: "Mengunjungi Cabang Madinah",
      t3text: "Museum kelas dunia yang menggabungkan teknologi modern dengan rasa hormat mendalam terhadap sejarah. Tur multibahasa sangat baik dan stafnya sangat ramah.",
      t3highlight: "Museum kelas dunia",
      t3name: "Mohammed Benzema",
      t3location: "Mengunjungi Cabang Rabat",
      t4text: "Kunjungan spiritual yang tak terlupakan! Saya merasakan kedekatan dengan Sirah Nabi ﷺ dengan cara yang tidak pernah saya bayangkan sebelumnya.",
      t4highlight: "Kunjungan spiritual yang tak terlupakan!",
      t4name: "Aisha Al-Mansoori",
      t4location: "Mengunjungi Cabang Dubai",
      t5text: "Pengalaman budaya terbaik yang pernah saya alami. Detail yang teliti di setiap sayap menunjukkan kepedulian dan cinta yang membangun museum ini.",
      t5highlight: "Pengalaman budaya terbaik yang pernah saya alami.",
      t5name: "Khalid Al-Otaibi",
      t5location: "Mengunjungi Cabang Jeddah",
      t6text: "Saya mengajak orang tua saya berwisata dan mereka sangat senang. Desainnya cocok untuk semua usia dan menyajikan informasi dengan cara yang lancar dan berkesan.",
      t6highlight: "Desainnya cocok untuk semua usia",
      t6name: "Sara Al-Qahtani",
      t6location: "Mengunjungi Cabang Riyadh",
      t7text: "Pengalaman edukatif yang luar biasa untuk anak-anak dan orang dewasa. Saya merekomendasikan setiap keluarga untuk mengunjungi museum ini.",
      t7highlight: "Pengalaman edukatif yang luar biasa",
      t7name: "Youssef Al-Harbi",
      t7location: "Mengunjungi Cabang Dammam",
      t8text: "Museum ini mewujudkan Sirah Nabi dengan luar biasa. Saya pulang dengan bangga akan sejarah Islam kami yang kaya.",
      t8highlight: "Museum ini mewujudkan Sirah Nabi dengan luar biasa.",
      t8name: "Noura Al-Subaie",
      t8location: "Mengunjungi Cabang Kuwait",
    },
    footer: {
      description: "Museum global yang merayakan warisan Islam dan menceritakan kisah Nabi ﷺ melalui teknologi terbaru dan pameran interaktif.",
      quickLinks: "Tautan Cepat",
      home: "Beranda",
      aboutMuseum: "Tentang Museum",
      exhibitions: "Pameran",
      events: "Acara",
      contactUs: "Hubungi Kami",
      branches: "Cabang Kami",
      branchMecca: "Cabang Mekah",
      branchMedina: "Cabang Madinah",
      branchRabat: "Cabang Rabat",
      branchNouakchott: "Cabang Nouakchott",
      branchDakar: "Cabang Dakar",
      contactTitle: "Hubungi Kami",
      address: "Mekah, Arab Saudi",
      copyright: "© 2024 Museum Sirah. Hak cipta dilindungi.",
      privacy: "Kebijakan Privasi",
      terms: "Syarat & Ketentuan",
    },
  },
};
